openapi: 3.0.1
info:
  title: Collateral Allocation Management
  description: The Service Domain manages the allocation of party owned assets to bank issued lending and other asset products.
  contact:
    name: BIAN
    url: https://bian.org
  version: 13.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/CollateralAllocationManagement/13.0.0
paths:
  '/CollateralAllocationManagement/{collateralallocationmanagementid}/Update':
    put:
      tags:
        - CR - CollateralAssetAllocation
      summary: Update Details of a collateral allocation
      description: Update Details of a collateral allocation
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/collateralallocationmanagementid'
      requestBody:
        $ref: '#/components/requestBodies/CollateralAssetAllocation'
      responses:
        '200':
          $ref: '#/components/responses/CollateralAssetAllocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CollateralAllocationManagement/{collateralallocationmanagementid}/Retrieve':
    get:
      tags:
        - CR - CollateralAssetAllocation
      summary: Retrieve details about a collateral allocation
      description: Retrieve details about a collateral allocation
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/collateralallocationmanagementid'
      responses:
        '200':
          $ref: '#/components/responses/CollateralAssetAllocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CollateralAllocationManagement/{collateralallocationmanagementid}/Exchange':
    put:
      tags:
        - CR - CollateralAssetAllocation
      summary: Accept or reject a collateral allocation proposal
      description: Accept or reject a collateral allocation proposal
      operationId: Exchange
      parameters:
        - $ref: '#/components/parameters/collateralallocationmanagementid'
      requestBody:
        $ref: '#/components/requestBodies/CollateralAssetAllocation'
      responses:
        '200':
          $ref: '#/components/responses/CollateralAssetAllocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CollateralAllocationManagement/{collateralallocationmanagementid}/Capture':
    put:
      tags:
        - CR - CollateralAssetAllocation
      summary: Capture Allocation of a Party Asset to a Lending Product
      description: Capture Allocation of a Party Asset to a Lending Product
      operationId: Capture
      parameters:
        - $ref: '#/components/parameters/collateralallocationmanagementid'
      requestBody:
        $ref: '#/components/requestBodies/CollateralAssetAllocation'
      responses:
        '200':
          $ref: '#/components/responses/CollateralAssetAllocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    value:
      type: object
      properties:
        Value:
          type: string
          description: "Data or set of data \n\n- A value is the concept of worth in general that is assigned or is determined by measurement, assessment or calculation. (UN/CEFACT)"
          format: datatype
      description: ''
    currencycode:
      type: object
      properties:
        Currencycode:
          type: string
          description: "A code identifying a currency according to ISO-4217.\nA currency is a system of money in general use in a particular country.\n\nCode allocated to a currency, by a maintenance agency, under an international identification scheme as described in the latest edition of the international standard ISO 4217 \"Codes for the representation of currencies and funds\". Valid currency codes are registered with the ISO 4217 Maintenance Agency, and consist of three contiguous letters. (ISO20022)\n\n"
          format: datatype
      description: ''
    text:
      type: object
      properties:
        Text:
          type: string
          description: Text is a character string such as a finite set of characters generally in the form of words of a language. (UN/CEFACT)
          format: datatype
      description: "The outcome of an evaluation of the acceptability of this party asset as collateral for this product instance; values are Accepted and Rejected ||\r\n|"
    amounttypevalues:
      enum:
        - Principal
        - Actual
        - Estimated
        - Maximum
        - Default
        - Replacement
        - Incremental
        - Decremental
        - Reserved
        - Available
        - Used
        - DuePayable
        - Minimum
        - Open
        - Unknown
        - Fixed
      type: string
      description: ">\r\n* `Principal` - \r\n* `Actual` - Actual amount.\r\n* `Estimated` - Estimated amount (the final amount could be above or below).\r\n* `Maximum` - Maximum amount (the final amount must be less or equal).\r\n* `Default` - Default amount.\r\n* `Replacement` - Replacement amount.\r\n* `Incremental` - Incremental amount for reservation.\r\n* `Decremental` - Decremental amount for reservation.\r\n* `Reserved` - Reserved or updated reserved amount for reservation.\r\n* `Available` - \r\n* `Used` - \r\n* `DuePayable` - \r\n* `Minimum` - \r\n* `Open` - The amount is open.(ISO20022)\r\n* `Unknown` - The amount is unkown.(ISO20022)\r\n* `Fixed` - The amount represents a fixed value.(ISO20022)\r\n"
    amount:
      type: object
      properties:
        AmountValue:
          $ref: '#/components/schemas/value'
        AmountCurrency:
          $ref: '#/components/schemas/currencycode'
        DecimalPointPosition:
          $ref: '#/components/schemas/text'
        AmountType:
          $ref: '#/components/schemas/amounttypevalues'
      description: The part of the collateral current value amount that has been tentatively assigned to the allocation of this asset as collateral to this product instance CurrencyAndAmount|CurrencyAndAmount (https://www.iso20022.org/standardsrepository/type/CurrencyAndAmount)|Standard|ISO20022  ()
    datetimetypevalues:
      enum:
        - MaturityDate
        - InitiatedDate
        - RequestedDate
        - ExecutedDate
        - OpenDate
        - CloseDate
        - ExpiryDate
        - EffectiveDate
        - CreatingDate
        - ActivationDate
        - DeactivationDate
        - BlockingDate
        - SendingDate
        - ValidFromDate
        - ValidToDate
        - ReceivingDate
        - SigningDate
        - DueDate
        - ValueDate
        - FulfillmentDate
      type: string
      description: ">\r\n* `MaturityDate` - \r\n* `InitiatedDate` - \r\n* `RequestedDate` - \r\n* `ExecutedDate` - \r\n* `OpenDate` - \r\n* `CloseDate` - \r\n* `ExpiryDate` - \r\n* `EffectiveDate` - \r\n* `CreatingDate` - \r\n* `ActivationDate` - \r\n* `DeactivationDate` - \r\n* `BlockingDate` - \r\n* `SendingDate` - \r\n* `ValidFromDate` - \r\n* `ValidToDate` - \r\n* `ReceivingDate` - \r\n* `SigningDate` - \r\n* `DueDate` - \r\n* `ValueDate` - \r\n* `FulfillmentDate` - \r\n"
    datetime:
      type: object
      properties:
        DateTimeContent:
          $ref: '#/components/schemas/text'
        TimeZoneCode:
          $ref: '#/components/schemas/text'
        DaylightSavingIndicator:
          $ref: '#/components/schemas/text'
        DateTimeType:
          $ref: '#/components/schemas/datetimetypevalues'
      description: The date on which the tentative assignment of the value amount to the allocation of this asset as collateral to this product instance becomes active ISODateTime|ISODateTime (https://www.iso20022.org/standardsrepository/type/ISODateTime)|Standard|ISO20022 BM ()
    schedule:
      type: object
      properties:
        ScheduleType:
          $ref: '#/components/schemas/text'
      description: "The schedule according to which the amount of the allocation of this party asset to this product instance as collateral is reduced ||\r\n|"
    collateralassetstatustypevalues:
      enum:
        - Offered
        - UnderAssessment
        - Transferred
        - Allocated
        - FreeForAllocation
        - AllocatedToAnotherLoan
        - IssuedForExecution
      type: string
      description: "The status of the collateral under consideration, e.g. Pending for use for allocating, Used for allocating, Pending for retirement for allocating ||\r\n|"
    partyassetdirectory:
      type: object
      properties:
        PartyAssetDirectory:
          type: string
          description: A registry to record Party Asset
          format: class
      description: "The reference to a party asset as recorded by Party Asset Directory ||\r\n|"
    name:
      type: object
      properties:
        Name:
          type: string
          description: 'A name is a word or phrase that constitutes the distinctive designation of a person, place, thing or concept. (UN/CEFAT)'
          format: datatype
      description: The name of the product to which the current party asset is allocated as collateral Name|Name (https://www.iso20022.org/standardsrepository/type/Name)|Standard|ISO20022 ()
    productagreementtypevalues:
      enum:
        - CurrentAccountAgreement
        - SavingsAccountAgreement
        - BrokeredProductAgreement
        - ConsumerLoanAgreement
        - MortgageLoanAgreement
        - DirectDebitServiceAgreement
        - TermDepositAgreement
      type: string
      description: ">\r\n* `CurrentAccountAgreement` - \r\n* `SavingsAccountAgreement` - \r\n* `BrokeredProductAgreement` - \r\n* `ConsumerLoanAgreement` - \r\n* `MortgageLoanAgreement` - \r\n* `DirectDebitServiceAgreement` - \r\n* `TermDepositAgreement` - \r\n"
    productagreement:
      type: object
      properties:
        ProductAgreementType:
          $ref: '#/components/schemas/productagreementtypevalues'
      description: "The reference to the product to which the current party asset is allocated as collateral ||\r\n|"
    CollateralAssetAllocation:
      type: object
      properties:
        CollateralAllocationAmount:
          $ref: '#/components/schemas/amount'
        CollateralAllocationDescription:
          $ref: '#/components/schemas/text'
        CollateralAllocationEndDate:
          $ref: '#/components/schemas/datetime'
        CollateralAllocationStartDate:
          $ref: '#/components/schemas/datetime'
        CollateralAllocationRecallAmount:
          $ref: '#/components/schemas/amount'
        CollateralAllocationRecallSchedule:
          $ref: '#/components/schemas/schedule'
        CollateralAllocationRecallResult:
          $ref: '#/components/schemas/text'
        CollateralCurrentValueAmount:
          $ref: '#/components/schemas/amount'
        CollateralEarmarkedAmount:
          $ref: '#/components/schemas/amount'
        CollateralEarmarkedEndDate:
          $ref: '#/components/schemas/datetime'
        CollateralEarmarkedStartDate:
          $ref: '#/components/schemas/datetime'
        CollateralStatus:
          $ref: '#/components/schemas/collateralassetstatustypevalues'
        PartyAssetDescription:
          $ref: '#/components/schemas/text'
        PartyAssetDirectoryReference:
          $ref: '#/components/schemas/partyassetdirectory'
        ProductInstanceName:
          $ref: '#/components/schemas/name'
        ProductInstanceReference:
          $ref: '#/components/schemas/productagreement'
        EvaluateAcceptabilityResultDescription:
          $ref: '#/components/schemas/text'
      description: "Maintain an inventory or holding of some resource and make assignments/allocations as requested  within Collateral Allocation Management. \nExample: Track the inventory and administer the distribution of central cash holdings throughout the branch & ATM network."
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    CollateralAssetAllocation:
      description: CollateralAssetAllocation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CollateralAssetAllocation'
  parameters:
    collateralallocationmanagementid:
      name: collateralallocationmanagementid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    CollateralAssetAllocation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CollateralAssetAllocation'
      required: true