openapi: 3.0.1
info:
  title: Card Terminal Administration
  description: This service domain administers the POS Network including the inventory, terminal characteristics, deployment and status of the POS devices.
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/BIAN-3/CardTerminalAdministration/10.0.0
paths:
  /CardTerminalAdministration/Provide:
    post:
      tags:
      - CR - CardPOSDeviceAllocation
      summary: PrCR Initial provision and registering of a point of sale (POS) device
      description: PrCR Initial provision and registering of a point of sale (POS) device
      operationId: Provide
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CardPOSDeviceAllocation'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvideCardPOSDeviceAllocationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardTerminalAdministration/{cardterminaladministrationId}/Update:
    put:
      tags:
      - CR - CardPOSDeviceAllocation
      summary: UpCR Update details about the POS device
      description: UpCR Update details about the POS device
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/CardTerminalAdministrationID'
      requestBody:
        $ref: '#/components/requestBodies/CardPOSDeviceAllocation'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardPOSDeviceAllocation'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardTerminalAdministration/{cardterminaladministrationId}/Retrieve:
    get:
      tags:
      - CR - CardPOSDeviceAllocation
      summary: ReCR Retrieve details about the POS device
      description: ReCR Retrieve details about the POS device
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CardTerminalAdministrationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardPOSDeviceAllocation'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardTerminalAdministration/{cardterminaladministrationId}/Allocation/Provide:
    post:
      tags:
      - BQ - Allocation
      summary: PrBQ Provide/allocate the device to a merchant
      description: PrBQ Provide/allocate the device to a merchant
      operationId: ProvideAllocation
      parameters:
      - $ref: '#/components/parameters/CardTerminalAdministrationID'
      requestBody:
        $ref: '#/components/requestBodies/ProvideAllocationRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvideAllocationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardTerminalAdministration/{cardterminaladministrationId}/Allocation/{allocationId}/Update:
    put:
      tags:
      - BQ - Allocation
      summary: UpBQ Update merchant allocation details
      description: UpBQ Update merchant allocation details
      operationId: UpdateAllocation
      parameters:
      - $ref: '#/components/parameters/CardTerminalAdministrationID'
      - $ref: '#/components/parameters/AllocationID'
      requestBody:
        $ref: '#/components/requestBodies/Allocation'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Allocation'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardTerminalAdministration/{cardterminaladministrationId}/Allocation/{allocationId}/Capture:
    put:
      tags:
      - BQ - Allocation
      summary: CaBQ Capture details about the allocation (e.g. report out of service state)
      description: CaBQ Capture details about the allocation (e.g. report out of service state)
      operationId: CaptureAllocation
      parameters:
      - $ref: '#/components/parameters/CardTerminalAdministrationID'
      - $ref: '#/components/parameters/AllocationID'
      requestBody:
        $ref: '#/components/requestBodies/CaptureAllocationRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaptureAllocationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardTerminalAdministration/{cardterminaladministrationId}/Allocation/{allocationId}/Grant:
    put:
      tags:
      - BQ - Allocation
      summary: GrBQ Obtain usage authorization grant for the device (may restrict usage)
      description: GrBQ Obtain usage authorization grant for the device (may restrict usage)
      operationId: GrantAllocation
      parameters:
      - $ref: '#/components/parameters/CardTerminalAdministrationID'
      - $ref: '#/components/parameters/AllocationID'
      requestBody:
        $ref: '#/components/requestBodies/GrantAllocationRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardTerminalAdministration/{cardterminaladministrationId}/Allocation/{allocationId}/Retrieve:
    get:
      tags:
      - BQ - Allocation
      summary: ReBQ Retrieve details about the POS device allocation
      description: ReBQ Retrieve details about the POS device allocation
      operationId: RetrieveAllocation
      parameters:
      - $ref: '#/components/parameters/CardTerminalAdministrationID'
      - $ref: '#/components/parameters/AllocationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveAllocationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CardPOSDeviceAllocation:
      type: object
      properties:
        CardPOSDeviceReference:
          type: object
        CardPOSDeviceIdentifier:
          type: string
        CardPOSDeviceType:
          type: string
        CardPOSDeviceSoftwareType:
          type: string
        CardPOSDeviceSoftwareVersion:
          type: string
        CardPOSDeviceAcquiredDate:
          type: string
        CardPOSRepairRecord:
          type: string
        CardPOSRepairDetails:
          type: string
        CardPOSRepairDates:
          type: string
        CardPOSDeviceStatus:
          type: string
    Allocation:
      type: object
      properties:
        MerchantReference:
          type: object
        MerchantType:
          type: string
        MerchantLocation:
          type: string
        CardPOSDeviceConfiguration:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    ProvideCardPOSDeviceAllocationResponse:
      type: object
      properties:
        CardPOSDeviceAllocation:
          type: object
          properties:
            CardPOSDeviceStatus:
              type: string
    ProvideAllocationRequest:
      type: object
      properties:
        CardPOSDeviceAllocation:
          type: object
          properties:
            CardPOSDeviceReference:
              type: object
            CardPOSDeviceIdentifier:
              type: string
            CardPOSDeviceType:
              type: string
            CardPOSDeviceSoftwareType:
              type: string
            CardPOSDeviceSoftwareVersion:
              type: string
            CardPOSDeviceStatus:
              type: string
        Allocation:
          type: object
          properties:
            MerchantReference:
              type: object
            MerchantType:
              type: string
            MerchantLocation:
              type: string
            CardPOSDeviceConfiguration:
              type: string
    ProvideAllocationResponse:
      type: object
      properties:
        CardPOSDeviceAllocation:
          type: object
          properties:
            CardPOSDeviceStatus:
              type: string
    CaptureAllocationRequest:
      type: object
      properties:
        CardPOSDeviceAllocation:
          type: object
          properties:
            CardPOSDeviceStatus:
              type: string
    CaptureAllocationResponse:
      type: object
      properties:
        CardPOSDeviceAllocation:
          type: object
          properties:
            CardPOSDeviceStatus:
              type: string
    GrantAllocationRequest:
      type: object
      properties:
        CardPOSDeviceAllocation:
          type: object
          properties:
            CardPOSDeviceReference:
              type: object
            CardPOSDeviceIdentifier:
              type: string
    RetrieveAllocationResponse:
      type: object
      properties:
        CardPOSDeviceAllocation:
          type: object
          properties:
            CardPOSDeviceReference:
              type: object
            CardPOSDeviceIdentifier:
              type: string
            CardPOSDeviceType:
              type: string
            CardPOSDeviceSoftwareType:
              type: string
            CardPOSDeviceSoftwareVersion:
              type: string
            CardPOSDeviceStatus:
              type: string
        Allocation:
          type: object
          properties:
            MerchantReference:
              type: object
            MerchantType:
              type: string
            MerchantLocation:
              type: string
            CardPOSDeviceConfiguration:
              type: string
  parameters:
    CardTerminalAdministrationID:
      name: cardterminaladministrationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    AllocationID:
      name: allocationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    CardPOSDeviceAllocation:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CardPOSDeviceAllocation'
    ProvideAllocationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProvideAllocationRequest'
    Allocation:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Allocation'
    CaptureAllocationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaptureAllocationRequest'
    GrantAllocationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GrantAllocationRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
