openapi: 3.0.1
info:
  title: Market Analysis
  description: This service domain analyzes internal and external market information sources as necessary to develop specific market insights. It may maintain a collection of predefined market analyses and may also offer specific ad-hoc analysis on request
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/BIAN-3/MarketAnalysis/10.0.0
paths:
  /MarketAnalysis/Evaluate:
    post:
      tags:
      - CR - GeneralMarketResearchAnalysis
      summary: EvCR Initialize a market research analysis
      description: EvCR Initialize a market research analysis
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateGeneralMarketResearchAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateGeneralMarketResearchAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /MarketAnalysis/{marketanalysisId}/Execute:
    put:
      tags:
      - CR - GeneralMarketResearchAnalysis
      summary: ExCR Obtain an automated refresh of market research analysis
      description: ExCR Obtain an automated refresh of market research analysis
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/MarketAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/ExecuteGeneralMarketResearchAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteGeneralMarketResearchAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /MarketAnalysis/{marketanalysisId}/Request:
    put:
      tags:
      - CR - GeneralMarketResearchAnalysis
      summary: RqCR Request a manual refresh of market research analysis
      description: RqCR Request a manual refresh of market research analysis
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/MarketAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/RequestGeneralMarketResearchAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestGeneralMarketResearchAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /MarketAnalysis/{marketanalysisId}/Retrieve:
    get:
      tags:
      - CR - GeneralMarketResearchAnalysis
      summary: ReCR Retrieve details about market research analysis, including recent results
      description: ReCR Retrieve details about market research analysis, including recent results
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/MarketAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveGeneralMarketResearchAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    GeneralMarketResearchAnalysis:
      type: object
      properties:
        GeneralMarketResearchAnalysisType:
          type: string
        GeneralMarketResearchAnalysisSpecification:
          type: string
        GeneralMarketResearchAnalysisGuidance:
          type: string
        GeneralMarketResearchAnalysisAlgorithmReference:
          type: object
        GeneralMarketResearchAnalysisRequestRecord:
          type: string
        GeneralMarketResearchAnalysisRequest:
          type: string
        EmployeeOrBusinessUnitReference:
          type: object
        MarketAnalysisRequestWorkProducts:
          type: string
        GeneralMarketResearchAnalysisRequestResult:
          type: string
        GeneralMarketResearchAnalysisUsageRecord:
          type: string
        GeneralMarketResearchAnalysisUsage:
          type: string
        GeneralMarketResearchAnalysisImpact:
          type: string
    AnalysisAlgorithm:
      type: object
      properties:
        AnalysisAlgorithmType:
          type: string
        AnalysisAlgorithmSpecification:
          type: string
        AnalysisAlgorithmGuidance:
          type: string
        AnalysisAlgorithmReferencedMarketResearchRecord:
          type: object
        MarketResearchReportTypeReference:
          type: string
        MarketResearchReportTypeDefinition:
          type: string
        MarketResearchReportVersion/Period:
          type: string
        MarketResearchReport:
          type: string
        GeneralMarketResearchDirectoryEntryInstanceReference:
          type: object
        AnalysisAlgorithmRequestRecord:
          type: string
        AnalysisAlgorithmRequest:
          type: string
        AnalysisAlgorithmWorkProducts:
          type: string
        AnalysisAlgorithmRequestResult:
          type: string
        AnalysisAlgorithmUsageRecord:
          type: string
        AnalysisAlgorithmUsage:
          type: string
        AnalysisAlgorithmImpact:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    EvaluateGeneralMarketResearchAnalysisRequest:
      type: object
      properties:
        GeneralMarketResearchAnalysis:
          type: object
          properties:
            GeneralMarketResearchAnalysisType:
              type: string
            GeneralMarketResearchAnalysisAlgorithmReference:
              type: object
            GeneralMarketResearchAnalysisRequestRecord:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            GeneralMarketResearchAnalysisUsageRecord:
              type: string
            GeneralMarketResearchAnalysisImpact:
              type: string
    EvaluateGeneralMarketResearchAnalysisResponse:
      type: object
      properties:
        GeneralMarketResearchAnalysis:
          type: object
          properties:
            GeneralMarketResearchAnalysisType:
              type: string
            GeneralMarketResearchAnalysisSpecification:
              type: string
            GeneralMarketResearchAnalysisGuidance:
              type: string
            GeneralMarketResearchAnalysisAlgorithmReference:
              type: object
            GeneralMarketResearchAnalysisRequestRecord:
              type: string
            MarketAnalysisRequestWorkProducts:
              type: string
            GeneralMarketResearchAnalysisRequestResult:
              type: string
            GeneralMarketResearchAnalysisUsageRecord:
              type: string
            GeneralMarketResearchAnalysisImpact:
              type: string
    ExecuteGeneralMarketResearchAnalysisRequest:
      type: object
      properties:
        GeneralMarketResearchAnalysis:
          type: object
          properties:
            GeneralMarketResearchAnalysisRequestRecord:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            GeneralMarketResearchAnalysisUsageRecord:
              type: string
            GeneralMarketResearchAnalysisImpact:
              type: string
    ExecuteGeneralMarketResearchAnalysisResponse:
      type: object
      properties:
        GeneralMarketResearchAnalysis:
          type: object
          properties:
            GeneralMarketResearchAnalysisRequestRecord:
              type: string
            MarketAnalysisRequestWorkProducts:
              type: string
            GeneralMarketResearchAnalysisRequestResult:
              type: string
    RequestGeneralMarketResearchAnalysisRequest:
      type: object
      properties:
        GeneralMarketResearchAnalysis:
          type: object
          properties:
            GeneralMarketResearchAnalysisRequestRecord:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            GeneralMarketResearchAnalysisUsageRecord:
              type: string
            GeneralMarketResearchAnalysisImpact:
              type: string
    RequestGeneralMarketResearchAnalysisResponse:
      type: object
      properties:
        GeneralMarketResearchAnalysis:
          type: object
          properties:
            GeneralMarketResearchAnalysisRequestRecord:
              type: string
            MarketAnalysisRequestWorkProducts:
              type: string
            GeneralMarketResearchAnalysisRequestResult:
              type: string
    RetrieveGeneralMarketResearchAnalysisResponse:
      type: object
      properties:
        GeneralMarketResearchAnalysis:
          type: object
          properties:
            GeneralMarketResearchAnalysisType:
              type: string
            GeneralMarketResearchAnalysisSpecification:
              type: string
            GeneralMarketResearchAnalysisGuidance:
              type: string
            GeneralMarketResearchAnalysisAlgorithmReference:
              type: object
            GeneralMarketResearchAnalysisRequestRecord:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            MarketAnalysisRequestWorkProducts:
              type: string
            GeneralMarketResearchAnalysisRequestResult:
              type: string
            GeneralMarketResearchAnalysisUsageRecord:
              type: string
            GeneralMarketResearchAnalysisImpact:
              type: string
  parameters:
    MarketAnalysisID:
      name: marketanalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    AnalysisAlgorithmID:
      name: analysisalgorithmId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateGeneralMarketResearchAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateGeneralMarketResearchAnalysisRequest'
    ExecuteGeneralMarketResearchAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecuteGeneralMarketResearchAnalysisRequest'
    RequestGeneralMarketResearchAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestGeneralMarketResearchAnalysisRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
