openapi: 3.0.1
info:
  title: Suitability Checking
  description: Confirm that all involved counterparties are suitable for a proposed market trade.
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/BIAN-3/SuitabilityChecking/10.0.0
paths:
  /SuitabilityChecking/Evaluate:
    post:
      tags:
      - CR - SuitabilityAssessment
      summary: EvCR Evaluate the suitability of a proposed transaction
      description: EvCR Evaluate the suitability of a proposed transaction
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateSuitabilityAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateSuitabilityAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SuitabilityChecking/{suitabilitycheckingId}/Update:
    put:
      tags:
      - CR - SuitabilityAssessment
      summary: UpCR Update details of a suitability evaluation
      description: UpCR Update details of a suitability evaluation
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/SuitabilityCheckingID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateSuitabilityAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSuitabilityAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SuitabilityChecking/{suitabilitycheckingId}/Request:
    put:
      tags:
      - CR - SuitabilityAssessment
      summary: RqCR Request manual intervention into an active evaluation
      description: RqCR Request manual intervention into an active evaluation
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/SuitabilityCheckingID'
      requestBody:
        $ref: '#/components/requestBodies/RequestSuitabilityAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestSuitabilityAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SuitabilityChecking/{suitabilitycheckingId}/Retrieve:
    get:
      tags:
      - CR - SuitabilityAssessment
      summary: ReCR Retrieve details about a suitability evaluation
      description: ReCR Retrieve details about a suitability evaluation
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/SuitabilityCheckingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveSuitabilityAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    SuitabilityAssessment:
      type: object
      properties:
        EmployeeOrBusinessUnitReference:
          type: object
        CustomerReference:
          type: object
        MarketOrderType:
          type: string
        InvestmentPortfolioInstanceReference:
          type: object
        CustomerMarketOrderProcessingInstruction:
          type: string
        ProposedMarketOrderTransaction:
          type: string
        InvestmentAccountArrangementInstanceReference:
          type: object
        SecurityType:
          type: string
        Amount:
          type: string
        DateType:
          type: string
        Date:
          type: string
        SuitabilityAssessmentType:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
        CorrespondenceInstanceReference:
          type: object
        SuitabilityComplianceAssessmentWorkProducts:
          type: string
        SuitabilityComplianceAssessmentResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    EvaluateSuitabilityAssessmentRequest:
      type: object
      properties:
        SuitabilityAssessment:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerReference:
              type: object
            MarketOrderType:
              type: string
            InvestmentPortfolioInstanceReference:
              type: object
            CustomerMarketOrderProcessingInstruction:
              type: string
            ProposedMarketOrderTransaction:
              type: string
            InvestmentAccountArrangementInstanceReference:
              type: object
            SecurityType:
              type: string
            Amount:
              type: string
            DateType:
              type: string
            SuitabilityAssessmentType:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
    EvaluateSuitabilityAssessmentResponse:
      type: object
      properties:
        SuitabilityAssessment:
          type: object
          properties:
            ProposedMarketOrderTransaction:
              type: string
            InvestmentAccountArrangementInstanceReference:
              type: object
            SecurityType:
              type: string
            Amount:
              type: string
            DateType:
              type: string
            SuitabilityAssessmentType:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            SuitabilityComplianceAssessmentWorkProducts:
              type: string
            SuitabilityComplianceAssessmentResult:
              type: string
    UpdateSuitabilityAssessmentRequest:
      type: object
      properties:
        SuitabilityAssessment:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerReference:
              type: object
            MarketOrderType:
              type: string
            InvestmentPortfolioInstanceReference:
              type: object
            CustomerMarketOrderProcessingInstruction:
              type: string
            ProposedMarketOrderTransaction:
              type: string
            InvestmentAccountArrangementInstanceReference:
              type: object
            SecurityType:
              type: string
            Amount:
              type: string
            DateType:
              type: string
            SuitabilityAssessmentType:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            SuitabilityComplianceAssessmentWorkProducts:
              type: string
            SuitabilityComplianceAssessmentResult:
              type: string
    UpdateSuitabilityAssessmentResponse:
      type: object
      properties:
        SuitabilityAssessment:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerReference:
              type: object
            MarketOrderType:
              type: string
            InvestmentPortfolioInstanceReference:
              type: object
            CustomerMarketOrderProcessingInstruction:
              type: string
            ProposedMarketOrderTransaction:
              type: string
            InvestmentAccountArrangementInstanceReference:
              type: object
            SecurityType:
              type: string
            Amount:
              type: string
            DateType:
              type: string
            SuitabilityAssessmentType:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            SuitabilityComplianceAssessmentWorkProducts:
              type: string
            SuitabilityComplianceAssessmentResult:
              type: string
    RequestSuitabilityAssessmentRequest:
      type: object
      properties:
        SuitabilityAssessment:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerReference:
              type: object
            MarketOrderType:
              type: string
            InvestmentPortfolioInstanceReference:
              type: object
            CustomerMarketOrderProcessingInstruction:
              type: string
            ProposedMarketOrderTransaction:
              type: string
            InvestmentAccountArrangementInstanceReference:
              type: object
            SecurityType:
              type: string
            Amount:
              type: string
            DateType:
              type: string
            SuitabilityAssessmentType:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            SuitabilityComplianceAssessmentWorkProducts:
              type: string
            SuitabilityComplianceAssessmentResult:
              type: string
    RequestSuitabilityAssessmentResponse:
      type: object
      properties:
        SuitabilityAssessment:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerMarketOrderProcessingInstruction:
              type: string
            ProposedMarketOrderTransaction:
              type: string
            InvestmentAccountArrangementInstanceReference:
              type: object
            SecurityType:
              type: string
            Amount:
              type: string
            DateType:
              type: string
            SuitabilityAssessmentType:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            SuitabilityComplianceAssessmentWorkProducts:
              type: string
            SuitabilityComplianceAssessmentResult:
              type: string
    RetrieveSuitabilityAssessmentResponse:
      type: object
      properties:
        SuitabilityAssessment:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerReference:
              type: object
            MarketOrderType:
              type: string
            InvestmentPortfolioInstanceReference:
              type: object
            CustomerMarketOrderProcessingInstruction:
              type: string
            ProposedMarketOrderTransaction:
              type: string
            InvestmentAccountArrangementInstanceReference:
              type: object
            SecurityType:
              type: string
            Amount:
              type: string
            DateType:
              type: string
            SuitabilityAssessmentType:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            SuitabilityComplianceAssessmentWorkProducts:
              type: string
            SuitabilityComplianceAssessmentResult:
              type: string
  parameters:
    SuitabilityCheckingID:
      name: suitabilitycheckingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateSuitabilityAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateSuitabilityAssessmentRequest'
    UpdateSuitabilityAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateSuitabilityAssessmentRequest'
    RequestSuitabilityAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestSuitabilityAssessmentRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
