openapi: 3.0.1
info:
  title: Syndicate Management
  description: This Service Domain manages syndicate membership and compliance
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/BIAN-3/SyndicateManagement/10.0.0
paths:
  /SyndicateManagement/{syndicatemanagementId}/Control:
    put:
      tags:
      - CR - SyndicateMembership
      summary: Control Syndicate Membership
      description: Control Syndicate Membership
      operationId: Control
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      requestBody:
        $ref: '#/components/requestBodies/SyndicateMembership'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateMembership'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/Grant:
    put:
      tags:
      - CR - SyndicateMembership
      summary: Grant Syndicate Membership
      description: Grant Syndicate Membership
      operationId: Grant
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      requestBody:
        $ref: '#/components/requestBodies/SyndicateMembership'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateMembership'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/Notify:
    get:
      tags:
      - CR - SyndicateMembership
      summary: Notify Syndicate Membership
      description: Notify Syndicate Membership
      operationId: Notify
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateMembership'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/Register:
    post:
      tags:
      - CR - SyndicateMembership
      summary: Register Syndicate Membership
      description: Register Syndicate Membership
      operationId: Register
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/SyndicateMembership'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateMembership'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/Request:
    put:
      tags:
      - CR - SyndicateMembership
      summary: Request Syndicate Membership
      description: Request Syndicate Membership
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      requestBody:
        $ref: '#/components/requestBodies/SyndicateMembership'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateMembership'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/Retrieve:
    get:
      tags:
      - CR - SyndicateMembership
      summary: Retrieve Syndicate Membership
      description: Retrieve Syndicate Membership
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateMembership'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/Update:
    put:
      tags:
      - CR - SyndicateMembership
      summary: Update Syndicate Membership
      description: Update Syndicate Membership
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      requestBody:
        $ref: '#/components/requestBodies/SyndicateMembership'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateMembership'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/SyndicateComplianceClauses/{syndicatecomplianceclausesId}/Notify:
    get:
      tags:
      - BQ - SyndicateComplianceClauses
      summary: Notify Syndicate Compliance Clauses
      description: Notify Syndicate Compliance Clauses
      operationId: NotifySyndicateComplianceClauses
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      - $ref: '#/components/parameters/SyndicateComplianceClausesID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateComplianceClauses'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/SyndicateEligibilityClauses/{syndicateeligibilityclausesId}/Notify:
    get:
      tags:
      - BQ - SyndicateEligibilityClauses
      summary: Notify Syndicate Eligibility Clauses
      description: Notify Syndicate Eligibility Clauses
      operationId: NotifySyndicateEligibilityClauses
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      - $ref: '#/components/parameters/SyndicateEligibilityClausesID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateEligibilityClauses'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/SyndicateComplianceClauses/{syndicatecomplianceclausesId}/Retrieve:
    get:
      tags:
      - BQ - SyndicateComplianceClauses
      summary: Retrieve Syndicate Compliance Clauses
      description: Retrieve Syndicate Compliance Clauses
      operationId: RetrieveSyndicateComplianceClauses
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      - $ref: '#/components/parameters/SyndicateComplianceClausesID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateComplianceClauses'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/SyndicateEligibilityClauses/{syndicateeligibilityclausesId}/Retrieve:
    get:
      tags:
      - BQ - SyndicateEligibilityClauses
      summary: Retrieve Syndicate Eligibility Clauses
      description: Retrieve Syndicate Eligibility Clauses
      operationId: RetrieveSyndicateEligibilityClauses
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      - $ref: '#/components/parameters/SyndicateEligibilityClausesID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateEligibilityClauses'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/SyndicateComplianceClauses/{syndicatecomplianceclausesId}/Update:
    put:
      tags:
      - BQ - SyndicateComplianceClauses
      summary: Update Syndicate Compliance Clauses
      description: Update Syndicate Compliance Clauses
      operationId: UpdateSyndicateComplianceClauses
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      - $ref: '#/components/parameters/SyndicateComplianceClausesID'
      requestBody:
        $ref: '#/components/requestBodies/SyndicateComplianceClauses'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateComplianceClauses'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /SyndicateManagement/{syndicatemanagementId}/SyndicateEligibilityClauses/{syndicateeligibilityclausesId}/Update:
    put:
      tags:
      - BQ - SyndicateEligibilityClauses
      summary: Update Syndicate Eligibility Clauses
      description: Update Syndicate Eligibility Clauses
      operationId: UpdateSyndicateEligibilityClauses
      parameters:
      - $ref: '#/components/parameters/SyndicateManagementID'
      - $ref: '#/components/parameters/SyndicateEligibilityClausesID'
      requestBody:
        $ref: '#/components/requestBodies/SyndicateEligibilityClauses'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyndicateEligibilityClauses'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    SyndicateMembership:
      type: object
      properties:
        SyndicateMembershipParameterType:
          type: string
        SyndicateMembershipSelectedOption:
          type: string
        SyndicateMembershipRequest:
          type: string
        SyndicateMembershipPlan:
          type: string
        SyndicateMembershipObligation:
          type: string
        SyndicateMembershipEntitlement:
          type: string
        SyndicateMembershipReference:
          type: object
    SyndicateEligibilityClauses:
      type: object
      properties:
        SyndicateMembershipReference:
          type: object
        SyndicateEligibilityClausesReference:
          type: object
        SyndicateEligibilityClausesType:
          type: string
        BusinessService:
          type: object
        BusinessUnit/EmployeeReference:
          type: object
        Postconditions:
          type: object
        Preconditions:
          type: object
        Schedule:
          type: object
    SyndicateComplianceClauses:
      type: object
      properties:
        SyndicateMembershipReference:
          type: object
        SyndicateComplianceClausesReference:
          type: object
        SyndicateComplianceClausesType:
          type: string
        BusinessService:
          type: object
        BusinessUnit/EmployeeReference:
          type: object
        Postconditions:
          type: object
        Preconditions:
          type: object
        Schedule:
          type: object
    SyndicateManagementOutcome:
      type: object
      properties:
        SyndicateManagementTask:
          type: string
        SyndicateManagementEntry:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    SyndicateManagementID:
      name: syndicatemanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    SyndicateEligibilityClausesID:
      name: syndicateeligibilityclausesId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    SyndicateComplianceClausesID:
      name: syndicatecomplianceclausesId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    SyndicateManagementOutcomeID:
      name: syndicatemanagementoutcomeId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    SyndicateMembership:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SyndicateMembership'
    SyndicateComplianceClauses:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SyndicateComplianceClauses'
    SyndicateEligibilityClauses:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SyndicateEligibilityClauses'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
