openapi: 3.0.1
info:
  title: Transaction Engine
  description: Orchestrate a schedule of payment transaction and reporting activities for the fulfillment of certain long term instruments or structured facilities
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/BIAN-3/TransactionEngine/10.0.0
paths:
  /TransactionEngine/Initiate:
    post:
      tags:
      - CR - TransactionScheduleFacility
      summary: InCR Initiate delegated transaction processing for a product instance
      description: InCR Initiate delegated transaction processing for a product instance
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/InitiateTransactionScheduleFacilityRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateTransactionScheduleFacilityResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /TransactionEngine/{transactionengineId}/Update:
    put:
      tags:
      - CR - TransactionScheduleFacility
      summary: UpCR Update details for an active transaction processing arrangement
      description: UpCR Update details for an active transaction processing arrangement
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/TransactionEngineID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateTransactionScheduleFacilityRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTransactionScheduleFacilityResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /TransactionEngine/{transactionengineId}/Execute:
    put:
      tags:
      - CR - TransactionScheduleFacility
      summary: ExCR Execute an automated function for a transaction processing arrangement
      description: ExCR Execute an automated function for a transaction processing arrangement
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/TransactionEngineID'
      requestBody:
        $ref: '#/components/requestBodies/ExecuteTransactionScheduleFacilityRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteTransactionScheduleFacilityResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /TransactionEngine/{transactionengineId}/Retrieve:
    get:
      tags:
      - CR - TransactionScheduleFacility
      summary: ReCR Retrieve details about delegated transaction processing for a product instance
      description: ReCR Retrieve details about delegated transaction processing for a product instance
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/TransactionEngineID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveTransactionScheduleFacilityResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    TransactionScheduleFacility:
      type: object
      properties:
        ProductInstanceReference:
          type: object
        ProductandServiceType:
          type: string
        TransactionScheduleFulfillmentSchedule:
          type: string
        TransactionScheduleWorkTaskRecord:
          type: string
        TransactionScheduleWorkTaskType:
          type: string
        TransactionScheduleWorkTaskDescription:
          type: string
        TransactionScheduleWorkTaskWorkProducts:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
        TransactionScheduleWorkTaskResult:
          type: string
        TransactionScheduleTaskFeeTransaction:
          type: string
        TransactionScheduleWorkTaskFeeTransactionDescription:
          type: string
        TransactionScheduleWorkTaskFeeTransactionType:
          type: string
        TransactionScheduleWorkTaskFeeTransactionCharge:
          type: string
        TransactionScheduleFinancialTransaction:
          type: string
        TransactionScheduleFinancialTransactionProductInstanceReference:
          type: object
        TransactionScheduleFinancialTransactionType:
          type: string
        TransactionScheduleFinancialTransactionDescription:
          type: string
        TransactionScheduleFinancialTransactionAmount:
          type: number
        CorrespondenceInstanceReference:
          type: object
        DateType:
          type: string
        Date:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    InitiateTransactionScheduleFacilityRequest:
      type: object
      properties:
        TransactionScheduleFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            ProductandServiceType:
              type: string
            TransactionScheduleFulfillmentSchedule:
              type: string
            TransactionScheduleWorkTaskRecord:
              type: string
            TransactionScheduleWorkTaskType:
              type: string
            TransactionScheduleWorkTaskWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            TransactionScheduleFinancialTransaction:
              type: string
            DateType:
              type: string
    InitiateTransactionScheduleFacilityResponse:
      type: object
      properties:
        TransactionScheduleFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            ProductandServiceType:
              type: string
            TransactionScheduleFulfillmentSchedule:
              type: string
            TransactionScheduleWorkTaskRecord:
              type: string
            TransactionScheduleWorkTaskType:
              type: string
            TransactionScheduleWorkTaskDescription:
              type: string
            TransactionScheduleWorkTaskWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            TransactionScheduleWorkTaskResult:
              type: string
            TransactionScheduleTaskFeeTransaction:
              type: string
            TransactionScheduleWorkTaskFeeTransactionDescription:
              type: string
            TransactionScheduleWorkTaskFeeTransactionType:
              type: string
            TransactionScheduleWorkTaskFeeTransactionCharge:
              type: string
            TransactionScheduleFinancialTransaction:
              type: string
            TransactionScheduleFinancialTransactionProductInstanceReference:
              type: object
            TransactionScheduleFinancialTransactionType:
              type: string
            TransactionScheduleFinancialTransactionDescription:
              type: string
            TransactionScheduleFinancialTransactionAmount:
              type: number
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
    UpdateTransactionScheduleFacilityRequest:
      type: object
      properties:
        TransactionScheduleFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            ProductandServiceType:
              type: string
            TransactionScheduleFulfillmentSchedule:
              type: string
            TransactionScheduleWorkTaskRecord:
              type: string
            TransactionScheduleWorkTaskType:
              type: string
            TransactionScheduleWorkTaskDescription:
              type: string
            TransactionScheduleWorkTaskWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            TransactionScheduleWorkTaskResult:
              type: string
            TransactionScheduleTaskFeeTransaction:
              type: string
            TransactionScheduleWorkTaskFeeTransactionDescription:
              type: string
            TransactionScheduleWorkTaskFeeTransactionType:
              type: string
            TransactionScheduleWorkTaskFeeTransactionCharge:
              type: string
            TransactionScheduleFinancialTransaction:
              type: string
            TransactionScheduleFinancialTransactionProductInstanceReference:
              type: object
            TransactionScheduleFinancialTransactionType:
              type: string
            TransactionScheduleFinancialTransactionDescription:
              type: string
            TransactionScheduleFinancialTransactionAmount:
              type: number
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
    UpdateTransactionScheduleFacilityResponse:
      type: object
      properties:
        TransactionScheduleFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            ProductandServiceType:
              type: string
            TransactionScheduleFulfillmentSchedule:
              type: string
            TransactionScheduleWorkTaskRecord:
              type: string
            TransactionScheduleWorkTaskType:
              type: string
            TransactionScheduleWorkTaskDescription:
              type: string
            TransactionScheduleWorkTaskWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            TransactionScheduleWorkTaskResult:
              type: string
            TransactionScheduleTaskFeeTransaction:
              type: string
            TransactionScheduleWorkTaskFeeTransactionDescription:
              type: string
            TransactionScheduleWorkTaskFeeTransactionType:
              type: string
            TransactionScheduleWorkTaskFeeTransactionCharge:
              type: string
            TransactionScheduleFinancialTransaction:
              type: string
            TransactionScheduleFinancialTransactionProductInstanceReference:
              type: object
            TransactionScheduleFinancialTransactionType:
              type: string
            TransactionScheduleFinancialTransactionDescription:
              type: string
            TransactionScheduleFinancialTransactionAmount:
              type: number
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
    ExecuteTransactionScheduleFacilityRequest:
      type: object
      properties:
        TransactionScheduleFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            ProductandServiceType:
              type: string
            TransactionScheduleFulfillmentSchedule:
              type: string
            TransactionScheduleWorkTaskRecord:
              type: string
            TransactionScheduleWorkTaskType:
              type: string
            TransactionScheduleWorkTaskWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            TransactionScheduleFinancialTransaction:
              type: string
            DateType:
              type: string
    ExecuteTransactionScheduleFacilityResponse:
      type: object
      properties:
        TransactionScheduleFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            ProductandServiceType:
              type: string
            TransactionScheduleFulfillmentSchedule:
              type: string
            TransactionScheduleWorkTaskRecord:
              type: string
            TransactionScheduleWorkTaskType:
              type: string
            TransactionScheduleWorkTaskDescription:
              type: string
            TransactionScheduleWorkTaskWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            TransactionScheduleWorkTaskResult:
              type: string
            TransactionScheduleTaskFeeTransaction:
              type: string
            TransactionScheduleWorkTaskFeeTransactionDescription:
              type: string
            TransactionScheduleWorkTaskFeeTransactionType:
              type: string
            TransactionScheduleWorkTaskFeeTransactionCharge:
              type: string
            TransactionScheduleFinancialTransaction:
              type: string
            TransactionScheduleFinancialTransactionProductInstanceReference:
              type: object
            TransactionScheduleFinancialTransactionType:
              type: string
            TransactionScheduleFinancialTransactionDescription:
              type: string
            TransactionScheduleFinancialTransactionAmount:
              type: number
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
    RetrieveTransactionScheduleFacilityResponse:
      type: object
      properties:
        TransactionScheduleFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            ProductandServiceType:
              type: string
            TransactionScheduleFulfillmentSchedule:
              type: string
            TransactionScheduleWorkTaskRecord:
              type: string
            TransactionScheduleWorkTaskType:
              type: string
            TransactionScheduleWorkTaskDescription:
              type: string
            TransactionScheduleWorkTaskWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            TransactionScheduleWorkTaskResult:
              type: string
            TransactionScheduleTaskFeeTransaction:
              type: string
            TransactionScheduleWorkTaskFeeTransactionDescription:
              type: string
            TransactionScheduleWorkTaskFeeTransactionType:
              type: string
            TransactionScheduleWorkTaskFeeTransactionCharge:
              type: string
            TransactionScheduleFinancialTransaction:
              type: string
            TransactionScheduleFinancialTransactionProductInstanceReference:
              type: object
            TransactionScheduleFinancialTransactionType:
              type: string
            TransactionScheduleFinancialTransactionDescription:
              type: string
            TransactionScheduleFinancialTransactionAmount:
              type: number
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
  parameters:
    TransactionEngineID:
      name: transactionengineId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    InitiateTransactionScheduleFacilityRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateTransactionScheduleFacilityRequest'
    UpdateTransactionScheduleFacilityRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateTransactionScheduleFacilityRequest'
    ExecuteTransactionScheduleFacilityRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecuteTransactionScheduleFacilityRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
