asyncapi: 3.0.0
info:
  title: Production Release
  version: 13.0.0
  description: >-
    BIAN Service Domain (expanded with the BIAN BOM) | Maintain and apply
    production release tests for new and updated systems
channels:
  ProductionSystemAssessment/Created:
    address: ProductionSystemAssessment/Created
    messages:
      ProductionSystemAssessment-created.message:
        $ref: '#/components/messages/ProductionSystemAssessment'
    description: ''
  ProductionSystemAssessment/Updated:
    address: ProductionSystemAssessment/Updated
    messages:
      ProductionSystemAssessment-updated.message:
        $ref: '#/components/messages/ProductionSystemAssessment'
    description: ''
  FunctionalRisk/Created:
    address: FunctionalRisk/Created
    messages:
      publish.message:
        $ref: '#/components/messages/FunctionalRisk'
    description: ''
  FunctionalRisk/Updated:
    address: FunctionalRisk/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/FunctionalRisk'
    description: ''
  ProductionRisk/Created:
    address: ProductionRisk/Created
    messages:
      publish.message:
        $ref: '#/components/messages/ProductionRisk'
    description: ''
  ProductionRisk/Updated:
    address: ProductionRisk/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/ProductionRisk'
    description: ''
  BusinessRisk/Created:
    address: BusinessRisk/Created
    messages:
      publish.message:
        $ref: '#/components/messages/BusinessRisk'
    description: ''
  BusinessRisk/Updated:
    address: BusinessRisk/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/BusinessRisk'
    description: ''
  OperationalRisk/Created:
    address: OperationalRisk/Created
    messages:
      publish.message:
        $ref: '#/components/messages/OperationalRisk'
    description: ''
  OperationalRisk/Updated:
    address: OperationalRisk/Updated
    messages:
      publish.message:
        $ref: '#/components/messages/OperationalRisk'
    description: ''
operations:
  ProductionSystemAssessment-created:
    action: receive
    channel:
      $ref: '#/channels/ProductionSystemAssessment~1Created'
    summary: ProductionSystemAssessment
    messages:
      - $ref: >-
          #/channels/ProductionSystemAssessment~1Created/messages/ProductionSystemAssessment-created.message
  ProductionSystemAssessment-updated:
    action: receive
    channel:
      $ref: '#/channels/ProductionSystemAssessment~1Updated'
    summary: ProductionSystemAssessment
    messages:
      - $ref: >-
          #/channels/ProductionSystemAssessment~1Updated/messages/ProductionSystemAssessment-updated.message
  FunctionalRisk/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/FunctionalRisk~1Created'
    summary: FunctionalRisk
    messages:
      - $ref: '#/channels/FunctionalRisk~1Created/messages/publish.message'
  FunctionalRisk/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/FunctionalRisk~1Updated'
    summary: FunctionalRisk
    messages:
      - $ref: '#/channels/FunctionalRisk~1Updated/messages/publish.message'
  ProductionRisk/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/ProductionRisk~1Created'
    summary: ProductionRisk
    messages:
      - $ref: '#/channels/ProductionRisk~1Created/messages/publish.message'
  ProductionRisk/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/ProductionRisk~1Updated'
    summary: ProductionRisk
    messages:
      - $ref: '#/channels/ProductionRisk~1Updated/messages/publish.message'
  BusinessRisk/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/BusinessRisk~1Created'
    summary: BusinessRisk
    messages:
      - $ref: '#/channels/BusinessRisk~1Created/messages/publish.message'
  BusinessRisk/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/BusinessRisk~1Updated'
    summary: BusinessRisk
    messages:
      - $ref: '#/channels/BusinessRisk~1Updated/messages/publish.message'
  OperationalRisk/Created.publish:
    action: receive
    channel:
      $ref: '#/channels/OperationalRisk~1Created'
    summary: OperationalRisk
    messages:
      - $ref: '#/channels/OperationalRisk~1Created/messages/publish.message'
  OperationalRisk/Updated.publish:
    action: receive
    channel:
      $ref: '#/channels/OperationalRisk~1Updated'
    summary: OperationalRisk
    messages:
      - $ref: '#/channels/OperationalRisk~1Updated/messages/publish.message'
components:
  messages:
    ProductionSystemAssessment:
      name: ProductionSystemAssessment
      description: >-
        To test or assess an entity, possibly against some formal qualification
        or certification requirement within Production Release. 
      payload:
        $ref: '#/components/schemas/ProductionSystemAssessment'
    FunctionalRisk:
      name: FunctionalRisk
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/FunctionalRisk'
    ProductionRisk:
      name: ProductionRisk
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/ProductionRisk'
    BusinessRisk:
      name: BusinessRisk
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/BusinessRisk'
    OperationalRisk:
      name: OperationalRisk
      description: |-
        All kind of verifications
        Examples:- Password verification
      payload:
        $ref: '#/components/schemas/OperationalRisk'
  schemas:
    FunctionalRisk:
      type: object
      description: ''
      properties:
        FunctionalRiskSystemTestType:
          $ref: '#/components/schemas/Text'
        FunctionalRiskSystemTestDescription:
          $ref: '#/components/schemas/Text'
        FunctionalRiskSystemTestWorkProduct:
          $ref: '#/components/schemas/Workproduct'
        FunctionalRiskSystemTestResult:
          $ref: '#/components/schemas/Test'
    Text:
      type: object
      format: Text
      description: ' '
      properties:
        Text:
          type: string
          format: DataType
          description: >-
            Text is a character string such as a finite set of characters
            generally in the form of words of a language. (UN/CEFACT) 
    Workproduct:
      type: object
      format: Workproduct
      description: "Reference to testing materials, results, assessments and other documents ||\r\n|"
      properties:
        Workproducttypevalues:
          enum:
            - Document
            - WorkingPaper
            - ActivityLog
            - Form
            - File
            - MeetingSchedule
            - MeetingMinute
          format: Workproduct
        WorkProductIdentifoication:
          $ref: '#/components/schemas/Identifier'
    Identifier:
      type: object
      format: Identifier
      description: ' '
      properties:
        IdentifierValue:
          $ref: '#/components/schemas/Value'
        IdentifierIssuingAuthority:
          $ref: '#/components/schemas/Involvedparty'
        Identifier:
          type: string
          format: DataType
          description: >-
            An identifier is a character string used to uniquely identify one
            instance of an object within an identification scheme that is
            managed by an agency. (UN/CEFAT) 
        IdentifierStartDate:
          $ref: '#/components/schemas/Datetime'
        IdentifierEndDate:
          $ref: '#/components/schemas/Datetime'
    Value:
      type: object
      format: Value
      description: ' '
      properties:
        Value:
          type: string
          format: DataType
          description: >-
            Data or set of data 


            A value is the concept of worth in general that is assigned or is
            determined by measurement, assessment or calculation. (UN/CEFACT) 
    Involvedparty:
      type: object
      format: Involvedparty
      description: 'Entity that assigns and manages the identification. '
      properties:
        PartyReference:
          $ref: '#/components/schemas/Party'
        PartyInvolvement:
          $ref: '#/components/schemas/Partyrole'
    Party:
      type: object
      format: Party
      description: ' '
      properties:
        PartyName:
          $ref: '#/components/schemas/Name'
        Partytypevalues:
          enum:
            - Person
            - Organisation
          format: Party
        PartyDateTime:
          $ref: '#/components/schemas/Datetime'
        PartyIdentification:
          $ref: '#/components/schemas/Partyidentification'
        Partylegalstructuretypevalues:
          enum:
            - Individual
            - CommunityInterestCompany
            - CharitableIncorporatedOrganisation
            - Co-Operative
            - Charity
            - GeneralPartnership
            - LimitedLiabilityPartnership
            - ScottishLimitedPartnership
            - LimitedPartnership
            - PrivateLimitedCompany
            - PublicLimitedCompany
            - Sole(SoleTrader)
          format: Party
    Name:
      type: object
      format: Name
      description: ' '
      properties:
        Name:
          type: string
          format: DataType
          description: >-
            A name is a word or phrase that constitutes the distinctive
            designation of a person, place, thing or concept. (UN/CEFAT) 
    Datetime:
      type: object
      format: Datetime
      description: ' '
      properties:
        DateTimeContent:
          $ref: '#/components/schemas/Text'
        TimeZoneCode:
          $ref: '#/components/schemas/Text'
        DaylightSavingIndicator:
          $ref: '#/components/schemas/Text'
        Datetimetypevalues:
          enum:
            - MaturityDate
            - InitiatedDate
            - RequestedDate
            - ExecutedDate
            - OpenDate
            - CloseDate
            - ExpiryDate
            - EffectiveDate
            - CreatingDate
            - ActivationDate
            - DeactivationDate
            - BlockingDate
            - SendingDate
            - ValidFromDate
            - ValidToDate
            - ReceivingDate
            - SigningDate
            - DueDate
            - ValueDate
            - FulfillmentDate
          format: Datetime
        Datetime:
          type: string
          format: DataType
          description: >-
            A date time identifies a date and time of day to various common
            resolutions: year, month, week, day, hour, minute, second, and
            fraction of second. (UN/CEFACT)


            A particular point in the progression of time defined by a mandatory
            date and a mandatory time component, expressed in either UTC time
            format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format
            (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format
            (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML
            Schema Part 2: Datatypes Second Edition W3C Recommendation 28
            October 2004" which is aligned with ISO 8601. (ISO20022)

            Note on the time format:

            1) beginning / end of calendar day

            00:00:00  -  the beginning of a calendar day

            24:00:00  -  the end of a calendar day

            2) fractions of second in time format

            Decimal fractions of seconds may be included. In this case, the
            involved parties shall agree on the maximum number of digits that
            are allowed. 
    Partyidentification:
      type: object
      format: Partyidentification
      description: ' '
      properties:
        Partyidentificationtypevalues:
          enum:
            - Taxidentificationnumber
            - Nationalregistrationnumber
            - Registrationauthorityidentificatio
            - LEI(LegalEntityIdentifier)
            - Alienregistrationnumber
            - Passportnumber
            - Taxexemptidentificationnumber
            - Corporateidentification
            - Driverlicensenumber
            - Foreigninvestmentidentitynumber
            - Socialsecuritynumber
            - Identitycardnumber
            - Concat
            - Nationalregistrationidentification
          format: Partyidentification
        PartyIdentification:
          $ref: '#/components/schemas/Identifier'
    Partyrole:
      type: object
      format: Partyrole
      description: ' '
      properties:
        PartyRoleType:
          $ref: '#/components/schemas/Text'
        PartyRoleName:
          $ref: '#/components/schemas/Name'
        PartyRoleValidityPeriod:
          $ref: '#/components/schemas/Datetimeperiod'
        Partyinvolvementtypevalues:
          enum:
            - Agreementinvolvement
            - Partyinvolvement
            - Arrangementinvolvement
            - Designspecificationinvolvement
            - Relationshipinvolvement
            - Locationinvolvement
            - Bankguaranteeinvolvement
          format: Partyrole
    Datetimeperiod:
      type: object
      format: Datetimeperiod
      description: ' '
      properties:
        FromDateTime:
          $ref: '#/components/schemas/Datetime'
        ToDateTime:
          $ref: '#/components/schemas/Datetime'
    Test:
      type: object
      format: Test
      description: "The result of the functional risk test (including required remedial actions/fixes where appropriate) ||\r\n|"
      properties:
        TestResult:
          $ref: '#/components/schemas/Text'
        TestGuidance:
          $ref: '#/components/schemas/Text'
        Testtypevalues:
          enum:
            - ProductEligibilityTest
            - NextBestProductTest
            - IssuedDeviceTest
            - CardHolderAuthenticationTest
            - CardFundsAvailableTest
            - CardTransactionFraudTest
            - CardStand-InAuthorizationTest
            - ExternalAccessRequestTest
            - SuitabilityTest
            - LegalComplianceTest
            - RegulatoryComplianceTest
            - SystemFunctionalTest
            - SystemProductionTest
            - SystemBusinessRiskTest
            - SystemOperationsTest
            - CreditPolicyComplianceTest
            - RuleSetAndDecisionTreeTest
            - ModelBasedTests
            - AssetAndLiabilityValuationTest
            - LiquidityAndCashFlowTest
            - RiskTest
            - SensitivityTest
          format: Test
        TestDescription:
          $ref: '#/components/schemas/Text'
    ProductionRisk:
      type: object
      description: ''
      properties:
        ProductionRiskSystemTestType:
          $ref: '#/components/schemas/Text'
        ProductionRiskSystemTestDescription:
          $ref: '#/components/schemas/Text'
        ProductionRiskSystemTestWorkProduct:
          $ref: '#/components/schemas/Workproduct'
        ProductionRiskSystemTestResult:
          $ref: '#/components/schemas/Test'
    BusinessRisk:
      type: object
      description: ''
      properties:
        BusinessRiskSystemTestType:
          $ref: '#/components/schemas/Text'
        BusinessRiskSystemTestDescription:
          $ref: '#/components/schemas/Text'
        BusinessRiskTestWorkProduct:
          $ref: '#/components/schemas/Workproduct'
        BusinessRiskTestResult:
          $ref: '#/components/schemas/Test'
    OperationalRisk:
      type: object
      description: ''
      properties:
        OperationalRiskSystemTestType:
          $ref: '#/components/schemas/Text'
        OperationalRiskSystemTestDescription:
          $ref: '#/components/schemas/Text'
        OperationalRiskSystemTestWorkProduct:
          $ref: '#/components/schemas/Workproduct'
        OperationalRiskSystemTestResult:
          $ref: '#/components/schemas/Test'
    ProductionSystemAssessment:
      type: object
      description: ''
      properties:
        ProductionReleaseName:
          $ref: '#/components/schemas/Name'
        EmployeeorBusinessUnitReference:
          $ref: '#/components/schemas/Involvedparty'
        ProductionReleaseType:
          $ref: '#/components/schemas/Text'
        ProductionReleaseDescription:
          $ref: '#/components/schemas/Text'
        ProductionReleaseTestProfile:
          $ref: '#/components/schemas/Profile'
        ProductionReleaseTestSchedule:
          $ref: '#/components/schemas/Schedule'
        ProductionReleaseConsolidationRecord:
          $ref: '#/components/schemas/Text'
        DocumentDirectoryEntryInstanceReference:
          $ref: '#/components/schemas/DocumentDirectoryEntry'
        Datetimetypevalues:
          enum:
            - MaturityDate
            - InitiatedDate
            - RequestedDate
            - ExecutedDate
            - OpenDate
            - CloseDate
            - ExpiryDate
            - EffectiveDate
            - CreatingDate
            - ActivationDate
            - DeactivationDate
            - BlockingDate
            - SendingDate
            - ValidFromDate
            - ValidToDate
            - ReceivingDate
            - SigningDate
            - DueDate
            - ValueDate
            - FulfillmentDate
        Date:
          $ref: '#/components/schemas/Datetime'
    Profile:
      type: object
      format: Profile
      description: "Details the types of production release tests to be and actually applied ||\r\n|"
      properties:
        Profile:
          type: string
          format: Class
          description: >-
            A brief description of the characteristics of something or someone.
            (Business Dictionary) 
    Schedule:
      type: object
      format: Schedule
      description: "The schedule for performing the range of release tests (planned and actual) ||\r\n|"
      properties:
        ScheduleType:
          $ref: '#/components/schemas/Text'
    DocumentDirectoryEntry:
      type: object
      format: DocumentDirectoryEntry
      description: "Reference to associated documents ||\r\n|"
      properties:
        DocumentDirectoryEntryIdentification:
          type: string
          format: String
          description: >-
            Identification allowing the retrieval of a document from a Document
            Directory 
