openapi: 3.0.1
info:
  title: Brokered Product Proxy
  description: This Service Domain oversees all activities associated with the coordinated delivery of 3rd party products and services
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/BrokeredProductProxy/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    ServiceAccess:
      type: object
      properties:
        ServiceAccessIdentifier:
          type: string
          description: An unique reference to an item or an occurrence of <BQ>
          format: Identifier
        ServiceAccessType:
          type: string
          description: ''
          format: Text
      description: ''
    BrokeredProductFacility:
      type: object
      properties:
        ConsentReference:
          type: string
          description: Reference to the Customer's account
          format: AccountAccessConsent
        ActiveAccessTokenReference:
          type: string
          description: ''
          format: Token
        BrokeredProductFacilityReference:
          type: string
          description: "An unique reference to an item or an occurrence of <CR>\n"
          format: Identifier
        ServiceProviderReference:
          type: string
          description: ''
          format: Involvedparty
        ServiceUserReference:
          type: string
          description: ''
          format: Involvedparty
        ThirdPartyProviderReference:
          type: string
          description: ''
          format: Involvedparty
      description: 'Oversee the working of a business unit, assign work, manage against a plan and troubleshoot issues within Brokered Product.'
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'