openapi: 3.0.1
info:
  title: Card Transaction Tracking
  description: 'Maintain a log of credit card bookings and authorizations for operational and management information, tracking and reconciliation purposes.'
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/CardTransactionTracking/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    CardTransactionEvent:
      type: object
      properties:
        Preconditions:
          type: string
          description: The required status/situation before the event is captured
          format: Condition
        Schedule:
          type: string
          description: The timing and key actions/milestones involved in capturing the event
          format: Schedule
        BusinessService:
          type: string
          description: The Card Transaction Event specific Business Service
          format: BusinessService
        Postconditions:
          type: string
          description: The completion status once the event has been captured
          format: Condition
        CreditCardPositionLogReference:
          type: string
          description: Reference to Card Transaction Event
          format: Log
        CardTransactionEventReference:
          type: string
          description: Reference to Card Transaction Event
          format: Event
        CardTransactionEventType:
          type: string
          description: The type of Card Transaction Event
          format: Text
      description: The Card Transaction Event is one of the specific types of events that is recorded in the Card Transaction Event
    CreditCardPositionKeepingOutcome:
      type: object
      properties:
        CreditCardPositionKeepingIncident:
          type: string
          description: ''
          format: Event
        CreditCardPositionKeepingLog:
          type: string
          description: ''
          format: Log
      description: The Card Transaction Event is one of the specific types of events that is recorded in the Card Transaction Event
    CreditCardPositionLog:
      type: object
      properties:
        CreditCardPositionLogParameterType:
          type: string
          description: A Classification value that distinguishes between business service events logged within Credit Card Position Log
          format: Featuretypevalues
        CreditCardPositionLogSelectedOption:
          type: string
          description: A selected optional business service as subject matter of Credit Card Position Log
          format: Service
        CreditCardPositionLogType:
          type: string
          description: The type of Credit Card Position Log
          format: Text
        CreditCardPositionLogSchedule:
          type: string
          description: Timetable to track Credit Card Position Log
          format: Schedule
        CreditCardPositionLogUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Credit Card Position Log
          format: Log
        CreditCardPositionLogUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Credit Card Position Log
          format: Log
        CreditCardPositionLogAssociatedParty:
          type: string
          description: Reference to the party who is involved in Credit Card Position Log
          format: Involvedparty
        CreditCardPositionLogBusinessUnitReference:
          type: string
          description: Reference to the business unit which is involved in Credit Card Position Log
          format: BusinessUnit
        CreditCardPositionLogCustomerReference:
          type: string
          description: Reference to the customer who is involved in Credit Card Position Log
          format: Involvedparty
        CreditCardPositionLogServiceConfiguration:
          type: string
          description: The configuration of Credit Card Position Log
          format: Text
        CreditCardPositionLogPosition:
          type: string
          description: The position of Credit Card Position Log
          format: Position
        CreditCardPositionLogPositionType:
          type: string
          description: A classification value expressing the kind of position withing the Credit Card Position Log
          format: PositionType
        CreditCardPositionLogPositionLimitTime:
          type: string
          description: Reference to the time limitation related to the position of Credit Card Position Log
          format: LimitArrangement
        CreditCardPositionLogReference:
          type: string
          description: An unique reference to an item or an occurrence of Credit Card Position Log
          format: Log
      description: 'Maintain a log of transactions or activity, typically a financial account/journal or a log of activity to support behavioral analysis within Credit Card Position Keeping. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'