openapi: 3.0.1
info:
  title: Claim Administration
  description: The claim administration Service Domain implements the payment and support obligations of the policy in respect to a verified claim
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/ClaimAdministration/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    Disbursement:
      type: object
      properties:
        DisbursementIdentification:
          type: string
          description: Unique identifier for the disbursement
          format: Identifier
          x-unique: true
          x-default: true
        ClaimReference:
          type: string
          description: Link to the associated claim
          format: Text
        PolicyReference:
          type: string
          description: Policy governing the payout
          format: Text
        BeneficiaryorPayeeReference:
          type: string
          description: Recipient of funds or services
          format: Involvedparty
        DisbursementAmount:
          type: string
          description: Total approved payout
          format: Amount
        DisbursementType:
          type: string
          description: 'Lump sum, partial, third-party payment, service payment'
          format: Text
        PaymentMethod:
          type: string
          description: 'Bank transfer, cheque, cash, EFT'
          format: Paymentmethodtypevalues
        PaymentInstructionReference:
          type: string
          description: Link to the payment order or instruction
          format: Text
        DisbursementTransactionStatus:
          type: string
          description: 'Pending, Sent, Confirmed, Reversed'
          format: Status
        DisbursementExecutionTimestamp:
          type: string
          description: Date/time payment was executed
          format: Datetime
        SettlementConfirmation:
          type: string
          description: Proof of payment or service fulfillment
          format: Text
        ClaimProcessingAdministrativePlanIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <CR>
          format: Text
          x-unique: true
          x-default: true
      description: The Disbursement is an activity that is performed as one aspect of carrying out the Disbursement
    Administration:
      type: object
      properties:
        AdministrativeTransactionIdentification:
          type: string
          description: Unique identifier for administrative action
          format: Identifier
          x-unique: true
          x-default: true
        ClaimReference:
          type: string
          description: Link to the claim being managed
          format: Text
        PolicyReference:
          type: string
          description: Insurance policy identifier
          format: Text
        AdministrativeTransactionType:
          type: string
          description: 'Case Initiation, Status Update, Adjustment, Escalation, Closure, Reopen'
          format: Administrativeclaimtransactiontypevalues
        AdministrativeTransactionInitiator:
          type: string
          description: Person/system performing the action
          format: Involvedparty
        AdministrativeTransactionTimestamp:
          type: string
          description: Date/time of transaction creation or update
          format: Datetime
        AdministrativeTransactionStatus:
          type: string
          description: 'Pending, In Progress, Completed, Escalated'
          format: Status
        AdministrativeTransactionOutcomeorResult:
          type: string
          description: 'Result of the administrative action (e.g., Case Opened, Claim Closed)'
          format: Text
        AdministrativeRelatedTransaction:
          type: string
          description: Link to previous or related administrative actions
          format: Transaction
        AdministrativeTransactionDescription:
          type: string
          description: Additional context or comments
          format: Text
        ClaimProcessingAdministrativePlanIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <CR>
          format: Text
          x-unique: true
          x-default: true
        AdministrationIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <BQ>
          format: Text
          x-unique: true
          x-default: true
      description: The Disbursement is an activity that is performed as one aspect of carrying out the Disbursement
    Documentation:
      type: object
      properties:
        DocumentIdentification:
          type: string
          description: Unique identifier for the document
          format: Identifier
          x-unique: true
          x-default: true
        ClaimReference:
          type: string
          description: Linked claim
          format: Text
        DocumentType:
          type: string
          description: 'Death certificate, invoice, proof of payment, correspondence'
          format: Documenttypevalues
        DocumentSourceorProviderReference:
          type: string
          description: 'Origin of the document (claimant, third-party, system)'
          format: Involvedparty
        DocumentStatus:
          type: string
          description: 'Pending, Verified, Approved, Archived'
          format: Status
        DocumentTimestamp:
          type: string
          description: Upload or verification date/time
          format: Datetime
        DocumentOwnerReference:
          type: string
          description: Person/system responsible for document handling
          format: Involvedparty
        DocumentLinkedTransaction:
          type: string
          description: 'Administrative, disbursement, or communication transaction the document supports'
          format: Transaction
        DocumentStorageLocationorReference:
          type: string
          description: System path or repository link
          format: Text
        ClaimProcessingAdministrativePlanIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <CR>
          format: Text
          x-unique: true
          x-default: true
        DocumentationIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <BQ>
          format: Text
          x-unique: true
          x-default: true
      description: The Disbursement is an activity that is performed as one aspect of carrying out the Disbursement
    Communication:
      type: object
      properties:
        CommunicationIdentification:
          type: string
          description: Unique identifier for the message
          format: Identifier
          x-unique: true
          x-default: true
        ClaimReference:
          type: string
          description: Linked claim
          format: Text
        CommunicationType:
          type: string
          description: 'Notification, inquiry, confirmation, reminder'
          format: Text
        CommunicationDirection:
          type: string
          description: Incoming / Outgoing
          format: Text
        CommunicationSenderorReceiverReference:
          type: string
          description: Party or system sending/receiving the message
          format: Involvedparty
        CommunicationChannel:
          type: string
          description: 'Email, SMS, letter, call, portal message'
          format: CommunicationChannel
        CommunicationContentorSubject:
          type: string
          description: Brief summary or body of communication
          format: Text
        CommunicationTimestamp:
          type: string
          description: Date/time of sending or receiving
          format: Datetime
        CommunicationStatus:
          type: string
          description: 'Pending, Sent, Delivered, Read, Acknowledged'
          format: Status
        CommunicationLinkedTransaction:
          type: string
          description: Related administrative or disbursement action
          format: Transaction
        ClaimProcessingAdministrativePlanIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <CR>
          format: Text
          x-unique: true
          x-default: true
      description: The Disbursement is an activity that is performed as one aspect of carrying out the Disbursement
    Negotiation:
      type: object
      properties:
        NegotiationIdentification:
          type: string
          description: Unique identifier for negotiation instance
          format: Identifier
          x-unique: true
          x-default: true
        ClaimReference:
          type: string
          description: Linked claim
          format: Text
        PolicyReference:
          type: string
          description: Policy terms relevant to negotiation
          format: Text
        NegotiationType:
          type: string
          description: 'Adjustment request, settlement dispute, partial payment, appeal'
          format: Text
        NegotiationInitiatorReference:
          type: string
          description: Person or system initiating negotiation
          format: Involvedparty
        NegotiationCounterpartyReference:
          type: string
          description: 'Other party involved in negotiation (claimant, provider)'
          format: Involvedparty
        NegotiationStatus:
          type: string
          description: 'Pending, Under Review, Resolved, Escalated'
          format: Status
        NegotiationTimestamp:
          type: string
          description: Start and end date/time of negotiation
          format: Datetime
        NegotiationOutcome:
          type: string
          description: 'Result of negotiation (approved, rejected, adjusted)'
          format: Text
        NegotiationLinkedTransaction:
          type: string
          description: 'Related disbursement, administrative, or communication activity'
          format: Transaction
        SupportingDocumentReference:
          type: string
          description: Evidence or documentation supporting negotiation
          format: Text
        ClaimProcessingAdministrativePlanIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <CR>
          format: Text
          x-unique: true
          x-default: true
      description: The Disbursement is an activity that is performed as one aspect of carrying out the Disbursement
    ClaimProcessingAdministrativePlan:
      type: object
      properties:
        ClaimAdministrationIdentification:
          type: string
          description: Unique identifier for this administrative case (top-level).
          format: Identifier
          x-unique: true
          x-default: true
        ClaimReference:
          type: string
          description: Link to the specific claim being administered.
          format: Text
        PolicyReference:
          type: string
          description: The insurance policy under which the claim is filed.
          format: Text
        ProductType:
          type: string
          description: 'Funeral policy type, benefit category, etc.'
          format: Funeralpolicyproducttypevalues
        ClaimantReference:
          type: string
          description: Customer submitting the claim.
          format: Involvedparty
        BeneficiaryorPayeeReference:
          type: string
          description: Person or organization entitled to benefits.
          format: Involvedparty
        ServiceProviderReference:
          type: string
          description: 'Funeral home, repatriation provider, etc.'
          format: Involvedparty
        InternalActorReference:
          type: string
          description: 'Claims agent, assessor, reviewer, approver.'
          format: Involvedparty
        ClaimAdministrationStatus:
          type: string
          description: 'Draft, Open, In Progress, Pending Documents, Approved, Settled, Closed, Reopened.'
          format: Status
        ClaimStage:
          type: string
          description: Initiation → Assessment → Administration → Settlement → Closure.
          format: Text
        StartDate:
          type: string
          description: When the administrative case is created.
          format: Datetime
        LastUpdatedDate:
          type: string
          description: Timestamp of most recent change.
          format: Datetime
        SLAorProcessingTimeline:
          type: string
          description: Required processing deadlines.
          format: Datetime
        ClaimProcessingAdministrativePlanIdentification:
          type: string
          description: A unique reference to an item or an occurrence of <CR>
          format: Text
          x-unique: true
          x-default: true
      description: 'Handle and assign the day to day activities, capture time, costs and income for an operational unit within Claim Administration. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'