openapi: 3.0.1
info:
  title: Claim Assessment
  description: The Claim Assessment Service Domain runs through the required tests to confirm the veracity of a claim made under an insurance policy.
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/ClaimAssessment/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    EligibilityCheck:
      type: object
      properties:
        ClaimValidationAssessmentIdentification:
          type: string
          description: "An unique reference to an item or an occurrence of Claim Validation Assessment\n"
          format: Text
          x-unique: true
          x-default: true
        EligibilityCheckIdentification:
          type: string
          description: An unique reference to an item or an occurrence of Eligibility Check
          format: Text
          x-unique: true
          x-default: true
        EligibilityCheckType:
          type: string
          description: The type of Eligibility Check
          format: Claimeligibilitychecktypevalues
        EligibilityCheckSubject:
          type: string
          description: The subject of Eligibility Check
          format: Text
        EligibilityCheckStatus:
          type: string
          description: The status of Eligibility Check
          format: Status
        EligibilityCheckSchedule:
          type: string
          description: Timetable used for Eligibility Check
          format: Schedule
        EligibilityCheckComplementedDate:
          type: string
          description: When Eligibility Check completed.
          format: Datetime
        EligibilityCheckResult:
          type: string
          description: The result of Eligibility Check
          format: Text
        EligibilityCheckAssociatedPartyReference:
          type: string
          description: Reference to Party who plays a specific role in Eligibility Check
          format: Involvedparty
      description: The Eligibility Check test is one aspect that can be intergrated into the overall Claim Validation Assessment
    EntitlementCheck:
      type: object
      properties:
        ClaimValidationAssessmentIdentification:
          type: string
          description: "An unique reference to an item or an occurrence of Claim Validation Assessment\n"
          format: Text
          x-unique: true
          x-default: true
        EntitlementCheckIdentification:
          type: string
          description: An unique reference to an item or an occurrence of Claim Entitlement
          format: Text
          x-unique: true
          x-default: true
        EntitlementCheckType:
          type: string
          description: The type of  Entitlement Check
          format: Claimentitlementchecktypevalues
        EntitlementCheckSubject:
          type: string
          description: The subject of Entitlement Check
          format: Text
        EntitlementCheckStatus:
          type: string
          description: The status of Entitlement Check
          format: Status
        EntitlementCheckSchedule:
          type: string
          description: Timetable used for Entitlement Check
          format: Schedule
        EntitlementCheckComplementedDate:
          type: string
          description: When Entitlement Check completed.
          format: ''
        EntitlementCheckResult:
          type: string
          description: The result of Entitlement Check
          format: Text
        EntitlementCheckAssociatedPartyReference:
          type: string
          description: Reference to Party who plays a specific role in Entitlement Check
          format: Involvedparty
      description: The Eligibility Check test is one aspect that can be intergrated into the overall Claim Validation Assessment
    Authentication:
      type: object
      properties:
        ClaimValidationAssessmentIdentification:
          type: string
          description: "An unique reference to an item or an occurrence of Claim Validation Assessment\n"
          format: Text
          x-unique: true
          x-default: true
        AuthenticationIdentification:
          type: string
          description: An unique reference to an item or an occurrence of Authentication
          format: Text
          x-unique: true
          x-default: true
        AuthenticationType:
          type: string
          description: The type of Authentication
          format: Authenticationtypevalues
        AuthenticationSubject:
          type: string
          description: The subject of Authentication
          format: Text
        AuthenticationStatus:
          type: string
          description: The status of Authentication
          format: Status
        AuthenticationSchedule:
          type: string
          description: Timetable used for Authentication
          format: Schedule
        AuthenticationComplementedDate:
          type: string
          description: When Authentication completed.
          format: Datetime
        AuthenticationResult:
          type: string
          description: The result of Authentication
          format: Text
        AuthenticationAssociatedPartyReference:
          type: string
          description: Reference to Party who plays a specific role in Authentication
          format: Involvedparty
      description: The Eligibility Check test is one aspect that can be intergrated into the overall Claim Validation Assessment
    ExternalAgencyEvaluation:
      type: object
      properties:
        ClaimValidationAssessmentIdentification:
          type: string
          description: "An unique reference to an item or an occurrence of Claim Validation Assessment\n"
          format: Text
          x-unique: true
          x-default: true
        ExternalAgencyEvaluationIdentification:
          type: string
          description: An unique reference to an item or an occurrence of External Agency Evaluation
          format: Text
          x-unique: true
          x-default: true
        ExternalAgencyEvaluationType:
          type: string
          description: The type of External Agency Evaluation
          format: Claimexternalagencychecktypevalues
        ExternalAgencyEvaluationSubject:
          type: string
          description: The subject of External Agency Evaluation
          format: Text
        ExternalAgencyEvaluationStatus:
          type: string
          description: The status of External Agency Evaluation
          format: Status
        ExternalAgencyEvaluationSchedule:
          type: string
          description: Timetable used for External Agency Evaluation
          format: Schedule
        ExternalAgencyEvaluationComplementedDate:
          type: string
          description: When External Agency Evaluation completed.
          format: Datetime
        ExternalAgencyEvaluationResult:
          type: string
          description: The result of External Agency Evaluation
          format: Text
        ExternalAgencyEvaluationAssociatedPartyReference:
          type: string
          description: Reference to Party who plays a specific role in External Agency Evaluation
          format: Involvedparty
      description: The Eligibility Check test is one aspect that can be intergrated into the overall Claim Validation Assessment
    ClaimValidationAssessment:
      type: object
      properties:
        ClaimAssessmentType:
          type: string
          description: The type of Claim Assessment
          format: Text
        ClaimValidationAssessmentIdentification:
          type: string
          description: An unique reference to an item or an occurrence of Claim Validation Assessment
          format: Text
          x-unique: true
          x-default: true
        ClaimAssessmentRequest:
          type: string
          description: Request to assess
          format: Instruction
        ClaimAssessmentSchedule:
          type: string
          description: Timetable to assess Claim Validation Assessment
          format: Schedule
        ClaimAssessmentStatus:
          type: string
          description: The status of Claim Validation Assessment
          format: Status
        ClaimAssessmentUsageLogReference:
          type: string
          description: Reference to the log of (usage) ativities/events of Claim Validation Assessment
          format: Text
        ClaimAssessmentRequesterReference:
          type: string
          description: Reference to Party who has requested Claim Validation Assessment
          format: Involvedparty
        ClaimAssessmentAssociatedPartyReference:
          type: string
          description: Reference to Party who is involved in Claim Validation Assessment
          format: Involvedparty
        ClaimAssessmentServiceProviderReference:
          type: string
          description: Reference to Party who has provided Claim Validation Assessment
          format: Involvedparty
        ClaimIdentification:
          type: string
          description: Unique identifier for claim tracking.
          format: Identifier
          x-unique: true
          x-default: true
        ClaimType:
          type: string
          description: 'Defines the nature of the claim (e.g., funeral, life, accident).'
          format: Text
        ClaimDate:
          type: string
          description: When claim was lodged and reported.
          format: Datetime
        PolicyReference:
          type: string
          description: 'Reference to Policy that Links claim to the insured agreement including Policy ID, Policy Status and Policy Coverage. '
          format: Text
        PolicyholderReference:
          type: string
          description: Reference to Partywho owns the policy
          format: Involvedparty
        ClaimAssessmentAssessorReference:
          type: string
          description: Reference to Party who assessed the claim.
          format: Involvedparty
        InsuredEventReference:
          type: string
          description: Reference to Event being claimed.
          format: Text
        ClaimAssessmentComplementedDate:
          type: string
          description: When assessment completed.
          format: Datetime
        ClaimAssessmentSupportingDocumentReference:
          type: string
          description: Reference to Document used in Claim Assessment
          format: Text
        ClaimAssessmentResult:
          type: string
          description: The result of Claim Validation Assessment
          format: Text
      description: 'To test or assess an entity, possibly against some formal qualification or certification requirement within Claim Assessment. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'