openapi: 3.0.1
info:
  title: Incentive Account
  description: 'This service domain orchestrates the scheduled maintenance and transactional activities associated with Incentive Program fulfillment, including enrollment, accrual and redemption. '
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/IncentiveAccount/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    IncentiveAccountFacility:
      type: object
      properties:
        IncentiveAccountFacilityAccountReference:
          type: string
          description: Reference to the account which is linked to Incentive Account Facility
          format: Account
        IncentiveAccountProductReference:
          type: string
          description: Reference to the product which is linked to Incentive Account Facility
          format: IncentiveProgram
        IncentiveAccountFacilityReference:
          type: string
          description: An unique reference to an item or an occurrence of Incentive Account Facility
          format: Identifier
        IncentiveAccountAgreementReference:
          type: string
          description: ''
          format: IncentiveAccountAgreement
        IncentiveAccountArrangementReference:
          type: string
          description: ''
          format: IncentiveAccountArrangement
        IncentiveAccountInvolvement:
          type: string
          description: ''
          format: IncentiveAccountInvolvement
      description: 'Fulfill any scheduled and ad-hoc obligations under a service arrangement, most typically for a financial product or facility within Incentive Account. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'