openapi: 3.0.1
info:
  title: Incentive Program Directory
  description: This service domain maintains specifications of the various Incentive Programs that are on offerr to customers.
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/IncentiveProgramDirectory/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    IncentiveProgramDirectoryEntry:
      type: object
      properties:
        IncentiveProgramDirectoryEntryDescription:
          type: string
          description: Documentation of Incentive Program Directory Entry
          format: Text
        IncentiveProgramDirectoryEntrySchedule:
          type: string
          description: The timetable to capture and maintain Incentive Program Directory Entry
          format: Schedule
        IncentiveProgramDirectoryEntryVersion:
          type: string
          description: The version of Incentive Program Directory Entry
          format: Number
        IncentiveProgramDirectoryEntryStatus:
          type: string
          description: The status of Incentive Program Directory Entry
          format: Status
        IncentiveProgramDirectoryEntryUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Incentive Program Directory Entry
          format: Log
        IncentiveProgramDirectoryEntryUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Incentive Program Directory Entry
          format: Log
        IncentiveProgramDirectoryEntryServiceConfiguration:
          type: string
          description: The configuration of Incentive Program Directory Entry
          format: Arrangement
        IncentiveProgramDirectoryEntryReference:
          type: string
          description: An unique reference to an item or an occurrence of Incentive Program Directory Entry
          format: Identifier
      description: Capture and maintain reference information about some type of entitity within Incentive Program Directory.
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'