openapi: 3.0.1
info:
  title: Interactive Help
  description: Operate the automated facility that provides interactive context sensitive servicing guidance to employees and self-serve customers
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/InteractiveHelp/14.0.0
paths:
  '/InteractiveHelp/{interactivehelpid}/HelpServiceSelection/Initiate':
    post:
      tags:
        - BQ - HelpServiceSelection
      summary: InBQ Initiate an interactive help service exchange
      description: InBQ Initiate an interactive help service exchange
      operationId: InitiateHelpServiceSelection
      parameters:
        - $ref: '#/components/parameters/interactivehelpid'
      requestBody:
        $ref: '#/components/requestBodies/HelpServiceSelection'
      responses:
        '200':
          $ref: '#/components/responses/HelpServiceSelection'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InteractiveHelp/{interactivehelpid}/HelpServiceSelection/{helpserviceselectionid}/Retrieve':
    get:
      tags:
        - BQ - HelpServiceSelection
      summary: ReBQ Retrieve details about an interactive help service exchange
      description: ReBQ Retrieve details about an interactive help service exchange
      operationId: RetrieveHelpServiceSelection
      parameters:
        - $ref: '#/components/parameters/interactivehelpid'
        - $ref: '#/components/parameters/helpserviceselectionid'
      responses:
        '200':
          $ref: '#/components/responses/HelpServiceSelection'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InteractiveHelp/{interactivehelpid}/HelpServiceSelection/{helpserviceselectionid}/Capture':
    put:
      tags:
        - BQ - HelpServiceSelection
      summary: CaBQ Capture user feedback relating to the service exchange
      description: CaBQ Capture user feedback relating to the service exchange
      operationId: CaptureHelpServiceSelection
      parameters:
        - $ref: '#/components/parameters/interactivehelpid'
        - $ref: '#/components/parameters/helpserviceselectionid'
      requestBody:
        $ref: '#/components/requestBodies/HelpServiceSelection'
      responses:
        '200':
          $ref: '#/components/responses/HelpServiceSelection'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InteractiveHelp/{interactivehelpid}/HelpServiceSelection/{helpserviceselectionid}/Execute':
    put:
      tags:
        - BQ - HelpServiceSelection
      summary: ExBQ Execute an automated action within the exchange
      description: ExBQ Execute an automated action within the exchange
      operationId: ExecuteHelpServiceSelection
      parameters:
        - $ref: '#/components/parameters/interactivehelpid'
        - $ref: '#/components/parameters/helpserviceselectionid'
      requestBody:
        $ref: '#/components/requestBodies/HelpServiceSelection'
      responses:
        '200':
          $ref: '#/components/responses/HelpServiceSelection'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    Producttypevalues:
      enum:
        - BankingProduct
        - InsuranceProduct
      type: string
      description: ">\r\n* `BankingProduct` - \r\n* `InsuranceProduct` - \r\n"
    Productfeaturetypevalues:
      enum:
        - Bankingservice
        - Administrationservice
        - Accessservice
        - Pricefeature
      type: string
      description: ">\r\n* `Bankingservice` - A classification that distinguishes between instances of product features according to the core banking services, functionality and/or objectives of banking.\n\ne.g. deposit services, exchange services, etc.\n\nThe primary reason for the contract with the client are the banking services. These services can be classified as follows:\n1. Selling services\n2. Financial Instruments Exchange\n3. Financial Stock Management\n4. Financial Transfers\n5. Financial Risk Transfer\n6. Business Operating\n7. Advisory\n8. Reporting\n\n\r\n* `Administrationservice` - A classification that distinguishes between instances of product features according to administrative tasks related to the Banking Product or Service.\r\n* `Accessservice` - A classification that distinguishes between product features according to way of the banking services can be accessed.\n\nThe access to services becomes more and more important in the evolving markets. \nWe need to separate different parts:\n1. The physical access to the infrastructure that allows access to the bank (where)\n2. The authorization of different parties to use the services of the bank (who)\n3. The agreed procedure to have access to different services (how)\n4. The services that are available for the different parties (what)\n\r\n* `Pricefeature` - A classification that distinguishes between instances of product features according to the cost/profit that is related to Banking Products or Services.\n\nIn all commercial offerings, there is an agreed cost for both parties (e.g. the interest arrangements are in both directions). The pricing structure of products or packages is a service that gives the possibility to the client to adapt his costs to his individual situation.\nWe see different generic categories in the pricing structure of the different products.\n1. Compensations\n2. Prices\n3. Fees\n4. Discounts\r\n"
    Task:
      type: object
      properties:
        Task:
          type: string
          description: ''
          format: DataType
      description: 'The user provided result of the interactive help service, including interaction statistics such as exchange frequency and duration'
    Involvedparty:
      type: object
      properties:
        PartyReference:
          type: string
          description: Reference to a Party who plays a specific role
          format: Text
        InvolvementReference:
          type: string
          description: Reference to a specific Role that is played by a Party
          format: Text
      description: 'Reference to the employee, business unit providing service feedback'
    Datetimetypevalues:
      enum:
        - MaturityDate
        - InitiatedDate
        - RequestedDate
        - ExecutedDate
        - OpenDate
        - CloseDate
        - ExpiryDate
        - EffectiveDate
        - CreatingDate
        - ActivationDate
        - DeactivationDate
        - BlockingDate
        - SendingDate
        - ValidFromDate
        - ValidToDate
        - ReceivingDate
        - SigningDate
        - DueDate
        - ValueDate
        - FulfillmentDate
        - EntryDate
      type: string
      description: ">\r\n* `MaturityDate` - \r\n* `InitiatedDate` - \r\n* `RequestedDate` - \r\n* `ExecutedDate` - \r\n* `OpenDate` - \r\n* `CloseDate` - \r\n* `ExpiryDate` - \r\n* `EffectiveDate` - \r\n* `CreatingDate` - \r\n* `ActivationDate` - \r\n* `DeactivationDate` - \r\n* `BlockingDate` - \r\n* `SendingDate` - \r\n* `ValidFromDate` - \r\n* `ValidToDate` - \r\n* `ReceivingDate` - \r\n* `SigningDate` - \r\n* `DueDate` - \r\n* `ValueDate` - \r\n* `FulfillmentDate` - \r\n* `EntryDate` - \r\n"
    Datetime:
      type: object
      properties:
        DateTimeContent:
          type: string
          description: The particular date and time point in the progression of time
          format: Text
        TimeZoneCode:
          type: string
          description: The time zone to which the date time refers.
          format: Text
        DaylightSavingIndicator:
          type: string
          description: ''
          format: Text
        DateTimeType:
          $ref: '#/components/schemas/Datetimetypevalues'
      description: 'The date, time (and duration) of the service usage'
    HelpServiceSelection:
      type: object
      properties:
        HelpSelectionInteractionType:
          type: string
          description: 'The type of session provides context for filtering content (e.g. employee, self-service customer)'
          format: Text
        HelpSelectionProductandServiceType:
          $ref: '#/components/schemas/Producttypevalues'
        HelpSelectionProductFeatureType:
          $ref: '#/components/schemas/Productfeaturetypevalues'
        SessionDialogueRecord:
          type: string
          description: The session dialogue log of actions during the contact to this point can be mined for key words that might improve the help selection
          format: Object
        HelpSelectionKeyWordMenu:
          type: string
          description: An interactive exchange can be supported where the service presents a menu of selection options or key words to narrow the search
          format: Object
        HelpSelectionKeyWordSelection:
          type: string
          description: The selected keyword or menu option
          format: Object
        InteractiveHelp:
          type: string
          description: The returned interactive help in any suitable form
          format: Object
        HelpSelectionTaskResult:
          $ref: '#/components/schemas/Task'
        HelpSelectionFeedback:
          type: string
          description: User provided commentary on the service provided
          format: Object
        EmployeeorBusinessUnitReference:
          $ref: '#/components/schemas/Involvedparty'
        DateandTime:
          $ref: '#/components/schemas/Datetime'
      description: "The collection of operational serivces/functions offered by the operational facility\n\nExamples: messages, capture, routines"
    interactiveHelpServiceOperatingSession:
      type: object
      description: 'Operate equipment and/or a largely automated facility within Interactive Help. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    HelpServiceSelection:
      description: HelpServiceSelection
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HelpServiceSelection'
  parameters:
    helpserviceselectionid:
      name: helpserviceselectionid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    HelpServiceSelection:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HelpServiceSelection'
      required: true