openapi: 3.0.1
info:
  title: Legal Advisory
  description: 'The role of the Service Domain is to provide customers and bank employees with advice on legal aspects of product sales and servicing as well as on planned and executed transactions. '
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/LegalAdvisory/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    Legal:
      type: object
      properties:
        LegalAdviceReference:
          type: string
          description: Reference to Legal
          format: Object
        LegalReference:
          type: string
          description: Reference to Legal
          format: Object
        LegalType:
          type: string
          description: The type of Legal
          format: Text
        BusinessService:
          type: string
          description: The Legal specific Business Service
          format: BusinessService
        BusinessUnitEmployeeReference:
          type: string
          description: The operating unit/employee responsible for providing the advice/recommendation
          format: Involvedparty
        Postconditions:
          type: string
          description: The completion status once the advice/recommendation has been provided
          format: Condition
        Preconditions:
          type: string
          description: The required status/situation before the advice/recommendation can be provided
          format: Condition
        Schedule:
          type: string
          description: The timing and key actions/milestones involved in providing the advice/recommendation
          format: Schedule
      description: The Legal advice is one specific topic that can be included in providing Legal
    Charge:
      type: object
      properties:
        LegalAdviceReference:
          type: string
          description: Reference to Service Fee
          format: Object
        ServiceFeeReference:
          type: string
          description: Reference to Service Fee
          format: Object
        ServiceFeeType:
          type: string
          description: The type of Service Fee
          format: Text
        BusinessService:
          type: string
          description: The Service Fee specific Business Service
          format: BusinessService
        BusinessUnitEmployeeReference:
          type: string
          description: The operating unit/employee responsible for providing the advice/recommendation
          format: Involvedparty
        Postconditions:
          type: string
          description: The completion status once the advice/recommendation has been provided
          format: Condition
        Preconditions:
          type: string
          description: The required status/situation before the advice/recommendation can be provided
          format: Condition
        Schedule:
          type: string
          description: The timing and key actions/milestones involved in providing the advice/recommendation
          format: Schedule
      description: The Legal advice is one specific topic that can be included in providing Legal
    LegalAdvice:
      type: object
      properties:
        LegalAdviceSubjectAreaType:
          type: string
          description: A Classification value that distinguishes between the subject matters of Legal Advice
          format: Text
        LegalAdviceParameterType:
          type: string
          description: A Classification value that distinguishes between Options defined within Legal Advice
          format: Featuretypevalues
        LegalAdviceSelectedOption:
          type: string
          description: 'A selected option, identified by Parameter Type'
          format: Feature
        LegalAdviceRequest:
          type: string
          description: Request to advise
          format: Instruction
        LegalAdviceUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events of Legal Advice
          format: Log
        LegalAdviceFeedback:
          type: string
          description: Information about reactions to an Advise which is used as a basis for improvement for the Legal Advice.
          format: Text
        LegalAdviceType:
          type: string
          description: A Classification value that distinguishes between the type of actions undertaken within Legal Advice
          format: Actiontype
        LegalAdviceReference:
          type: string
          description: An unique reference to an item or an occurrence of Legal Advice
          format: Object
      description: Provide specialist advice and/or support as an ongoing service or for a specific task/event within Legal Advisory
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'