openapi: 3.0.1
info:
  title: Operations Log
  description: This service domain handle the day-to-day operations of a collaborative partner related services.
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/OperationsLog/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    PartnerEventLog:
      type: object
      properties:
        PartnerEventLogParameterType:
          type: string
          description: A Classification value that distinguishes between business service events logged within Partner Event Log
          format: BIANVersion14.0.0ForPublication
        PartnerEventLogSelectedOption:
          type: string
          description: A selected optional business service as subject matter of Partner Event Log
          format: Service
        PartnerEventLogType:
          type: string
          description: The type of Partner Event Log
          format: Text
        PartnerEventLogSchedule:
          type: string
          description: Timetable to track Partner Event Log
          format: Schedule
        PartnerEventLogUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Partner Event Log
          format: Log
        PartnerEventLogUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Partner Event Log
          format: Log
        PartnerEventLogAssociatedParty:
          type: string
          description: Reference to the party who is involved in Partner Event Log
          format: Involvedparty
        PartnerEventLogBusinessUnitReference:
          type: string
          description: Reference to the business unit which is involved in Partner Event Log
          format: BusinessUnit
        PartnerEventLogCustomerReference:
          type: string
          description: Reference to the customer who is involved in Partner Event Log
          format: Involvedparty
        PartnerEventLogServiceConfiguration:
          type: string
          description: The configuration of Partner Event Log
          format: Text
        PartnerEventLogPosition:
          type: string
          description: The position of Partner Event Log
          format: Position
        PartnerEventLogPositionType:
          type: string
          description: A classification value expressing the kind of position withing the Partner Event Log
          format: PositionType
        PartnerEventLogPositionLimitTime:
          type: string
          description: Reference to the time limitation related to the position of Partner Event Log
          format: LimitArrangement
        PartnerEventLogReference:
          type: string
          description: An unique reference to an item or an occurrence of Partner Event Log
          format: Log
      description: 'Maintain a log of transactions or activity, typically a financial account/journal or a log of activity to support behavioral analysis within Operations Log. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'