openapi: 3.0.1
info:
  title: Partner Management
  description: 'This service domain handles strategic management of collaborative partners including partner development, performance and relationship tracking.'
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/PartnerManagement/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    PartnerReleationshipManagementPlan:
      type: object
      properties:
        PartnerReleationshipManagementPlanType:
          type: string
          description: The type of Partner Releationship Management Plan
          format: Plantype
        PartnerReleationshipManagementPlanReference:
          type: string
          description: An unique reference to an item or an occurrence of Partner Releationship Management Plan
          format: Plan
        PartnerReleationshipManagementPlanBudgetType:
          type: string
          description: A Classification value that distinguishes between Budgets within Partner Releationship Management Plan according to the type of resource and/or activity that is budgetted
          format: Budgettype
        PartnerReleationshipManagementPlanBudget:
          type: string
          description: Amount of budget which is arranged whitin Partner Releationship Management Plan
          format: Amount
        PartnerReleationshipManagementPlanAssignment:
          type: string
          description: The assignment of a required activity to a responsibe party in Partner Releationship Management Plan
          format: Assignment
        PartnerReleationshipManagementPlanDuty:
          type: string
          description: The set of management responsibilities defined in Partner Releationship Management Plan
          format: Arrangement
        PartnerReleationshipManagementPlanDescription:
          type: string
          description: Documentation of Partner Releationship Management Plan
          format: Text
        PartnerReleationshipManagementPlanBudgetBalance:
          type: string
          description: Balance of budget which is arranged whitin Partner Releationship Management Plan
          format: Accountbalance
        PartnerReleationshipManagementPlanAssociatedParty:
          type: string
          description: Party who is involved in Partner Releationship Management Plan
          format: Involvedparty
        PartnerReleationshipManagementPlanSubjectMatter:
          type: string
          description: The subject matter of Partner Releationship Management Plan
          format: Object
      description: 'Oversee the working of a business unit, assign work, manage against a plan and troubleshoot issues within Partner Management.'
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'