openapi: 3.0.1
info:
  title: Partner Administration
  description: This service domain handle the day-to-day operations of a collaborative partner related services.
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/PartnerAdministration/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    PartnerAdministrativePlan:
      type: object
      properties:
        PartnerAdministrativePlanBudgetType:
          type: string
          description: A Classification value that distinguishes between Budgets within Partner Administrative Plan according to the type of resource and/or activity that is budgetted
          format: Budgettype
        PartnerAdministrativePlanBudget:
          type: string
          description: Amount of budget which is arranged whitin Partner Administrative Plan
          format: Amount
        PartnerAdministrativePlanAssignment:
          type: string
          description: The assignment of a required activity to a responsibe party in Partner Administrative Plan
          format: Assignment
        PartnerAdministrativePlanDuty:
          type: string
          description: The set of administrative responsibilities defined in Partner Administrative Plan
          format: Arrangement
        PartnerAdministrativePlanAssociatedParty:
          type: string
          description: Party who is involved in Partner Administrative Plan
          format: Involvedparty
        PartnerAdministrativePlanBudgetBalance:
          type: string
          description: Balance of budget which is arranged whitin Partner Administrative Plan
          format: Accountbalance
        PartnerAdministrativePlanSubjectMatter:
          type: string
          description: The subject matter of Partner Administrative Plan
          format: Subject
        PartnerAdministrativePlanType:
          type: string
          description: The type of Partner Administrative Plan
          format: Plantype
        PartnerAdministrativePlanReference:
          type: string
          description: An unique reference to an item or an occurrence of Partner Administrative Plan
          format: Plan
        PartnerAdministrativePlanDescription:
          type: string
          description: Documentation of Partner Administrative Plan
          format: Text
      description: 'Handle and assign the day to day activities, capture time, costs and income for an operational unit within Partner Administration. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'