openapi: 3.0.1
info:
  title: Rewards Delivery
  description: The service domain orchestrates the entire end-to-end  process for delivering a redeemed reward.
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/RewardsDelivery/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    RewardsDeliveryProcedure:
      type: object
      properties:
        RewardsDeliveryProcedureParameterType:
          type: string
          description: A Classification value that distinguishes between Procedures according to the type of business services and/or type of concern defined within Rewards Delivery Procedure
          format: Featuretypevalues
        RewardsDeliveryProcedureSelectedOption:
          type: string
          description: A selected optional business service as subject matter of Rewards Delivery Procedure
          format: Feature
        RewardsDeliveryProcedureRequest:
          type: string
          description: Request to process Rewards Delivery Procedure
          format: Instruction
        RewardsDeliveryProcedureSchedule:
          type: string
          description: Timetable to process Rewards Delivery Procedure
          format: Schedule
        RewardsDeliveryProcedureStatus:
          type: string
          description: The status of Rewards Delivery Procedure
          format: Status
        RewardsDeliveryProcedureAssociatedPartyReference:
          type: string
          description: Reference to the party who is involved in Rewards Delivery Procedure
          format: Involvedparty
        RewardsDeliveryProcedureBusinessUnitReference:
          type: string
          description: Reference to the business unit which is involved in Rewards Delivery Procedure
          format: Involvedparty
        RewardsDeliveryProcedureServiceProviderReference:
          type: string
          description: Reference to the party who is the service provider of Rewards Delivery Procedure
          format: Involvedparty
        RewardsDeliveryProcedureFinancialFacilityReference:
          type: string
          description: Reference to the Financial Facility related to Rewards Delivery Procedure
          format: FinancialFacility
        RewardsDeliveryProcedureEmployeeReference:
          type: string
          description: Reference to the employee who is involved in Rewards Delivery Procedure
          format: Involvedparty
        RewardsDeliveryProcedureCustomerReference:
          type: string
          description: Reference to the customer who is involved in Rewards Delivery Procedure
          format: Involvedparty
        RewardsDeliveryProcedureType:
          type: string
          description: A Classification value that distinguishes between the type of process undertaken within Rewards Delivery Procedure
          format: Proceduretype
        RewardsDeliveryProcedureServiceProviderSchedule:
          type: string
          description: The schedule according to which the service provider will process the Rewards Delivery Procedure
          format: Schedule
        RewardsDeliveryProcedureServiceType:
          type: string
          description: A Classification value that distinguishes between the type of services in Rewards Delivery Procedure
          format: Servicetype
        RewardsDeliveryProcedureProductandServiceType:
          type: string
          description: A Classification value that distinguishes between the type of products/services related to Rewards Delivery Procedure
          format: Bankingproducttype
        RewardsDeliveryProcedureProductandServiceInstance:
          type: string
          description: Reference to the product or service that is related to Rewards Delivery Procedure
          format: Product
        RewardsDeliveryProcedureTransactionType:
          type: string
          description: A Classification value that distinguishes between the type of transactions in Rewards Delivery Procedure
          format: Transactiontype
        RewardsDeliveryProcedureTransaction:
          type: string
          description: Reference to the transaction that is related to Rewards Delivery Procedure
          format: Transaction
        RewardsDeliveryProcedureFinancialTransactionArrangement:
          type: string
          description: Reference to the Financial Transaction Arrangement that is related to Rewards Delivery Procedure
          format: Arrangement
        RewardsDeliveryProcedureCustomerAgreementReference:
          type: string
          description: Reference to the Customer Agreement that is related to Rewards Delivery Procedure
          format: Agreement
        RewardsDeliveryProcedureReference:
          type: string
          description: An unique reference to an item or an occurrence of Rewards Delivery Procedure
          format: Procedure
      description: 'Complete work tasks following a defined procedure in support of general office activities and product and service delivery within Rewards Delivery. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'