openapi: 3.0.1
info:
  title: Rewards Menu
  description: 'The service domain presents a set of eligible rewards a customer can select from. '
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/RewardsMenu/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    RewardsOptionDirectoryEntry:
      type: object
      properties:
        RewardsOptionDirectoryEntryDescription:
          type: string
          description: Documentation of Rewards Option Directory Entry
          format: Text
        RewardsOptionDirectoryEntrySchedule:
          type: string
          description: The timetable to capture and maintain Rewards Option Directory Entry
          format: Schedule
        RewardsOptionDirectoryEntryVersion:
          type: string
          description: The version of Rewards Option Directory Entry
          format: Number
        RewardsOptionDirectoryEntryStatus:
          type: string
          description: The status of Rewards Option Directory Entry
          format: Status
        RewardsOptionDirectoryEntryUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Rewards Option Directory Entry
          format: Log
        RewardsOptionDirectoryEntryUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Rewards Option Directory Entry
          format: Log
        RewardsOptionDirectoryEntryServiceConfiguration:
          type: string
          description: The configuration of Rewards Option Directory Entry
          format: Arrangement
        RewardsOptionDirectoryEntryReference:
          type: string
          description: An unique reference to an item or an occurrence of Rewards Option Directory Entry
          format: Identifier
      description: Capture and maintain reference information about some type of entitity within Rewards Menu.
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'