openapi: 3.0.1
info:
  title: Rewards Inventory
  description: The service domain handles the allocation of rewards from available inventory.
  contact:
    name: BIAN
    url: https://bian.org
  version: 14.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/RewardsInventory/14.0.0
paths: { }
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    RewardsInventoryAllocation:
      type: object
      properties:
        RewardsInventoryAllocationParameterType:
          type: string
          description: A Classification value that distinguishes between allocation Options according to the optional business services defined within Rewards Inventory Allocation
          format: Featuretypevalues
        RewardsInventoryAllocationSelectedOption:
          type: string
          description: A selected optional business service for which resources are allocated
          format: Feature
        RewardsInventoryAllocationType:
          type: string
          description: 'A Classification value, that distinguishes between the the type of resource allocated withing the Rewards Inventory Allocation'
          format: Text
        RewardsInventoryAllocationDescription:
          type: string
          description: Documentation of Rewards Inventory Allocation
          format: Text
        RewardsInventoryAllocationRequest:
          type: string
          description: Request to allocate Rewards Inventory
          format: Instruction
        RewardsInventoryAllocationSchedule:
          type: string
          description: Timetable to allocate Rewards Inventory
          format: Schedule
        RewardsInventoryAllocationStatus:
          type: string
          description: The status of Rewards Inventory Allocation
          format: Allocationstatustypevalues
        RewardsInventoryAllocationReference:
          type: string
          description: Reference to the party who is involved in Rewards Inventory Allocation
          format: Allocation
        RewardsInventoryAllocationCustomerReference:
          type: string
          description: Reference to the customer who is involved in Rewards Inventory Allocation
          format: Involvedparty
        RewardsInventoryAllocationCurrency:
          type: string
          description: The curreny which is arranged/used for Rewards Inventory Allocation
          format: Currencycode
        RewardsInventoryAllocationRegulationReference:
          type: string
          description: Reference to the regulation which is defined for Rewards Inventory Allocation
          format: RuleSet
        RewardsInventoryAllocationRegulationType:
          type: string
          description: A Classification that distinguishes between the regularity domains of Rewards Inventory Allocation
          format: Rulesettypevalues
        RewardsInventoryAllocationJurisdiction:
          type: string
          description: Reference to the jurisdiction that is assigned to Rewards Inventory Allocation in case of legal dispute.
          format: Jurisdiction
        RewardsInventoryAllocationBookingLocation:
          type: string
          description: 'The financial accounting unit into which the financial events, with regard to the origination and fulfillment of the agreement, are entered.'
          format: Location
        RewardsInventoryAllocationAccountType:
          type: string
          description: The type of account which is linked to Rewards Inventory Allocation
          format: Accounttypevalues
        RewardsInventoryAllocationAccountReference:
          type: string
          description: Reference to the account which is linked to Rewards Inventory Allocation
          format: Account
        RewardsInventoryAllocationInstance:
          type: string
          description: Reference to Rewards Inventory Allocation Instance
          format: Identifier
      description: "Maintain an inventory or holding of some resource and make assignments/allocations as requested  within Rewards Inventory. \nExample: Track the inventory and administer the distribution of central cash holdings throughout the branch & ATM network."
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'