openapi: 3.0.1
info:
  title: Correspondent Bank Directory
  description: This service domain maintains correspondent bank reference details. This includes correspondent bank payment parameters in particular bank limits and capturing transaction activity to track reciprocity
  contact:
    name: BIAN
    url: https://bian.org
  version: 12.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/CorrespondentBankDirectory/12.0.0
paths:
  /CorrespondentBankDirectory/Register:
    post:
      tags:
        - CR - CorrespondentBankDirectoryEntry
      summary: InCR Register a new correspondent bank in the catalog
      description: InCR Register a new correspondent bank in the catalog
      operationId: Register
      requestBody:
        $ref: '#/components/requestBodies/RegisterCorrespondentBankDirectoryEntryRequest'
      responses:
        '200':
          $ref: '#/components/responses/RegisterCorrespondentBankDirectoryEntryRequest'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CorrespondentBankDirectory/{correspondentbankdirectoryid}/Update':
    put:
      tags:
        - CR - CorrespondentBankDirectoryEntry
      summary: UpCR Update details of a correspondent bank in the catalog
      description: UpCR Update details of a correspondent bank in the catalog
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/correspondentbankdirectoryid'
      requestBody:
        $ref: '#/components/requestBodies/UpdateCorrespondentBankDirectoryEntryRequest'
      responses:
        '200':
          $ref: '#/components/responses/UpdateCorrespondentBankDirectoryEntryResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CorrespondentBankDirectory/{correspondentbankdirectoryid}/Request':
    put:
      tags:
        - CR - CorrespondentBankDirectoryEntry
      summary: RqCR Request that an existing entry is updated or revised
      description: RqCR Request that an existing entry is updated or revised
      operationId: Request
      parameters:
        - $ref: '#/components/parameters/correspondentbankdirectoryid'
      requestBody:
        $ref: '#/components/requestBodies/RequestCorrespondentBankDirectoryEntryRequest'
      responses:
        '200':
          $ref: '#/components/responses/RequestCorrespondentBankDirectoryEntryResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CorrespondentBankDirectory/{correspondentbankdirectoryid}/Retrieve':
    get:
      tags:
        - CR - CorrespondentBankDirectoryEntry
      summary: ReCR Retrieve correspondent bank details from the catalog
      description: ReCR Retrieve correspondent bank details from the catalog
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/correspondentbankdirectoryid'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveCorrespondentBankDirectoryEntryResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    CorrespondentBankDirectoryEntry:
      type: object
      properties:
        CorrespondentBankReference:
          type: string
          description: Reference to the correspondent bank (e.g. BIC Codes)
          format: object
        ClearingSortCodes:
          type: string
          description: Clearing and sorting code used in payment processing
          format: string
        ContactAddresses:
          type: string
          description: Contact details for key parties at the bank
          format: string
        LegalEntityIdentifiers:
          type: string
          description: One or more associated legal entity references associated with the bank
          format: string
        BankHierarchy:
          type: string
          description: A description of the legal entity hierarchy at the bank
          format: string
        HolidayTimezoneSchedule:
          type: string
          description: A reference to the bank calendar details for payment processing
          format: string
        VostroAccountReference:
          type: string
          description: Reference to associated vostro account (your money at our bank)
          format: object
        NostroMirrorAccountReference:
          type: string
          description: Reference to associated nostro account (our money at your bank)
          format: object
        CorrespondentBankAgreementReference:
          type: string
          description: 'Reference to the bank agreement (that will detail limits, fees, preferred payments mechanism)'
          format: object
        CorrespondentBankAgreement:
          type: string
          description: 'The correspondent bank agreement (details agreed limits, fees, preferred payments mechanism, etc.)'
          format: string
      description: Capture and maintain reference information about some type of entitity within Correspondent Bank Data Management.
    RegisterCorrespondentBankDirectoryEntryRequest:
      type: object
      properties:
        CorrespondentBankDirectoryEntry:
          type: object
          properties:
            CorrespondentBankReference:
              type: string
              description: "\r\n"
              format: object
            ClearingSortCodes:
              type: string
              description: "\r\n"
              format: string
            ContactAddresses:
              type: string
              description: "\r\n"
              format: string
            LegalEntityIdentifiers:
              type: string
              description: "\r\n"
              format: string
            BankHierarchy:
              type: string
              description: "\r\n"
              format: string
            HolidayTimezoneSchedule:
              type: string
              description: "\r\n"
              format: string
            VostroAccountReference:
              type: string
              description: "\r\n"
              format: object
            NostroMirrorAccountReference:
              type: string
              description: "\r\n"
              format: object
            CorrespondentBankAgreementReference:
              type: string
              description: "\r\n"
              format: object
      description: 'Input: InCR Register a new correspondent bank in the catalog'
    UpdateCorrespondentBankDirectoryEntryRequest:
      type: object
      properties:
        CorrespondentBankDirectoryEntry:
          type: object
          properties:
            CorrespondentBankReference:
              type: string
              description: "\r\n"
              format: object
            ClearingSortCodes:
              type: string
              description: "\r\n"
              format: string
            ContactAddresses:
              type: string
              description: "\r\n"
              format: string
            LegalEntityIdentifiers:
              type: string
              description: "\r\n"
              format: string
            BankHierarchy:
              type: string
              description: "\r\n"
              format: string
            HolidayTimezoneSchedule:
              type: string
              description: "\r\n"
              format: string
            VostroAccountReference:
              type: string
              description: "\r\n"
              format: object
            NostroMirrorAccountReference:
              type: string
              description: "\r\n"
              format: object
            CorrespondentBankAgreementReference:
              type: string
              description: "\r\n"
              format: object
      description: 'Input: UpCR Update details of a correspondent bank in the catalog'
    UpdateCorrespondentBankDirectoryEntryResponse:
      type: object
      properties:
        CorrespondentBankDirectoryEntry:
          type: object
          properties:
            CorrespondentBankReference:
              type: string
              description: "\r\n"
              format: object
            ClearingSortCodes:
              type: string
              description: "\r\n"
              format: string
            ContactAddresses:
              type: string
              description: "\r\n"
              format: string
            LegalEntityIdentifiers:
              type: string
              description: "\r\n"
              format: string
            BankHierarchy:
              type: string
              description: "\r\n"
              format: string
            HolidayTimezoneSchedule:
              type: string
              description: "\r\n"
              format: string
            VostroAccountReference:
              type: string
              description: "\r\n"
              format: object
            NostroMirrorAccountReference:
              type: string
              description: "\r\n"
              format: object
            CorrespondentBankAgreementReference:
              type: string
              description: "\r\n"
              format: object
      description: 'Output: UpCR Update details of a correspondent bank in the catalog'
    RequestCorrespondentBankDirectoryEntryRequest:
      type: object
      properties:
        CorrespondentBankDirectoryEntry:
          type: object
          properties:
            CorrespondentBankReference:
              type: string
              description: "\r\n"
              format: object
            ClearingSortCodes:
              type: string
              description: "\r\n"
              format: string
            ContactAddresses:
              type: string
              description: "\r\n"
              format: string
            LegalEntityIdentifiers:
              type: string
              description: "\r\n"
              format: string
            BankHierarchy:
              type: string
              description: "\r\n"
              format: string
            HolidayTimezoneSchedule:
              type: string
              description: "\r\n"
              format: string
            VostroAccountReference:
              type: string
              description: "\r\n"
              format: object
            NostroMirrorAccountReference:
              type: string
              description: "\r\n"
              format: object
            CorrespondentBankAgreementReference:
              type: string
              description: "\r\n"
              format: object
      description: 'Input: RqCR Request that an existing entry is updated or revised'
    RequestCorrespondentBankDirectoryEntryResponse:
      type: object
      properties:
        CorrespondentBankDirectoryEntry:
          type: object
          properties:
            CorrespondentBankReference:
              type: string
              description: "\r\n"
              format: object
            ClearingSortCodes:
              type: string
              description: "\r\n"
              format: string
            ContactAddresses:
              type: string
              description: "\r\n"
              format: string
            LegalEntityIdentifiers:
              type: string
              description: "\r\n"
              format: string
            BankHierarchy:
              type: string
              description: "\r\n"
              format: string
            HolidayTimezoneSchedule:
              type: string
              description: "\r\n"
              format: string
            VostroAccountReference:
              type: string
              description: "\r\n"
              format: object
            NostroMirrorAccountReference:
              type: string
              description: "\r\n"
              format: object
            CorrespondentBankAgreementReference:
              type: string
              description: "\r\n"
              format: object
      description: 'Output: RqCR Request that an existing entry is updated or revised'
    RetrieveCorrespondentBankDirectoryEntryResponse:
      type: object
      properties:
        CorrespondentBankDirectoryEntry:
          type: object
          properties:
            CorrespondentBankReference:
              type: string
              description: "\r\n"
              format: object
            ClearingSortCodes:
              type: string
              description: "\r\n"
              format: string
            ContactAddresses:
              type: string
              description: "\r\n"
              format: string
            LegalEntityIdentifiers:
              type: string
              description: "\r\n"
              format: string
            BankHierarchy:
              type: string
              description: "\r\n"
              format: string
            HolidayTimezoneSchedule:
              type: string
              description: "\r\n"
              format: string
            VostroAccountReference:
              type: string
              description: "\r\n"
              format: object
            NostroMirrorAccountReference:
              type: string
              description: "\r\n"
              format: object
            CorrespondentBankAgreementReference:
              type: string
              description: "\r\n"
              format: object
      description: 'Output: ReCR Retrieve correspondent bank details from the catalog'
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    RegisterCorrespondentBankDirectoryEntryRequest:
      description: RegisterCorrespondentBankDirectoryEntryRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterCorrespondentBankDirectoryEntryRequest'
    UpdateCorrespondentBankDirectoryEntryResponse:
      description: UpdateCorrespondentBankDirectoryEntryResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateCorrespondentBankDirectoryEntryResponse'
    RequestCorrespondentBankDirectoryEntryResponse:
      description: RequestCorrespondentBankDirectoryEntryResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestCorrespondentBankDirectoryEntryResponse'
    RetrieveCorrespondentBankDirectoryEntryResponse:
      description: RetrieveCorrespondentBankDirectoryEntryResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveCorrespondentBankDirectoryEntryResponse'
  parameters:
    correspondentbankdirectoryid:
      name: correspondentbankdirectoryid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    RegisterCorrespondentBankDirectoryEntryRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterCorrespondentBankDirectoryEntryRequest'
      required: true
    UpdateCorrespondentBankDirectoryEntryRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateCorrespondentBankDirectoryEntryRequest'
      required: true
    RequestCorrespondentBankDirectoryEntryRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestCorrespondentBankDirectoryEntryRequest'
      required: true