openapi: 3.0.1
info:
  title: Credit Card Position Keeping
  description: 'Maintain a log of credit card bookings and authorizations for operational and management information, tracking and reconciliation purposes.'
  contact:
    name: BIAN
    url: https://bian.org
  version: 11.0.0
servers:
  - url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/CreditCardPositionKeeping/11.0.0
paths:
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/Capture':
    put:
      tags:
        - CR - CreditCardPositionLog
      summary: Capture Credit Card Position Log
      description: Capture Credit Card Position Log
      operationId: Capture
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        '200':
          $ref: '#/components/responses/CreditCardPositionLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/Control':
    put:
      tags:
        - CR - CreditCardPositionLog
      summary: Control Credit Card Position Log
      description: Control Credit Card Position Log
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        '200':
          $ref: '#/components/responses/CreditCardPositionLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/Initiate:
    post:
      tags:
        - CR - CreditCardPositionLog
      summary: Initiate Credit Card Position Log
      description: Initiate Credit Card Position Log
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        '200':
          $ref: '#/components/responses/CreditCardPositionLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/Notify':
    get:
      tags:
        - CR - CreditCardPositionLog
      summary: Notify Credit Card Position Log
      description: Notify Credit Card Position Log
      operationId: Notify
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
      responses:
        '200':
          $ref: '#/components/responses/CreditCardPositionLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/Retrieve':
    get:
      tags:
        - CR - CreditCardPositionLog
      summary: Retrieve Credit Card Position Log
      description: Retrieve Credit Card Position Log
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
      responses:
        '200':
          $ref: '#/components/responses/CreditCardPositionLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/Update':
    put:
      tags:
        - CR - CreditCardPositionLog
      summary: Update Credit Card Position Log
      description: Update Credit Card Position Log
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        '200':
          $ref: '#/components/responses/CreditCardPositionLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/CardTransactionEvent/{cardtransactioneventid}/Capture':
    put:
      tags:
        - BQ - CardTransactionEvent
      summary: Capture Card Transaction Event
      description: Capture Card Transaction Event
      operationId: CaptureCardTransactionEvent
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
        - $ref: '#/components/parameters/cardtransactioneventid'
      requestBody:
        $ref: '#/components/requestBodies/CardTransactionEvent'
      responses:
        '200':
          $ref: '#/components/responses/CardTransactionEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/CardTransactionEvent/{cardtransactioneventid}/Notify':
    get:
      tags:
        - BQ - CardTransactionEvent
      summary: Notify Card Transaction Event
      description: Notify Card Transaction Event
      operationId: NotifyCardTransactionEvent
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
        - $ref: '#/components/parameters/cardtransactioneventid'
      responses:
        '200':
          $ref: '#/components/responses/CardTransactionEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/CardTransactionEvent/{cardtransactioneventid}/Retrieve':
    get:
      tags:
        - BQ - CardTransactionEvent
      summary: Retrieve Card Transaction Event
      description: Retrieve Card Transaction Event
      operationId: RetrieveCardTransactionEvent
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
        - $ref: '#/components/parameters/cardtransactioneventid'
      responses:
        '200':
          $ref: '#/components/responses/CardTransactionEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditCardPositionKeeping/{creditcardpositionkeepingid}/CardTransactionEvent/{cardtransactioneventid}/Update':
    put:
      tags:
        - BQ - CardTransactionEvent
      summary: Update Card Transaction Event
      description: Update Card Transaction Event
      operationId: UpdateCardTransactionEvent
      parameters:
        - $ref: '#/components/parameters/creditcardpositionkeepingid'
        - $ref: '#/components/parameters/cardtransactioneventid'
      requestBody:
        $ref: '#/components/requestBodies/CardTransactionEvent'
      responses:
        '200':
          $ref: '#/components/responses/CardTransactionEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    CardTransactionEvent:
      type: object
      properties:
        Preconditions:
          type: string
          description: The required status/situation before the event is captured
          format: condition
        Schedule:
          type: string
          description: The timing and key actions/milestones involved in capturing the event
          format: schedule
        BusinessService:
          type: string
          description: The Card Transaction Event specific Business Service
          format: businessservice
        Postconditions:
          type: string
          description: The completion status once the event has been captured
          format: condition
        CreditCardPositionLogReference:
          type: string
          description: Reference to Card Transaction Event
          format: log
        CardTransactionEventReference:
          type: string
          description: Reference to Card Transaction Event
          format: event
        CardTransactionEventType:
          type: string
          description: The type of Card Transaction Event
          format: text
      description: The Card Transaction Event is one of the specific types of events that is recorded in the Card Transaction Event
    CreditCardPositionKeepingOutcome:
      type: object
      properties:
        CreditCardPositionKeepingIncident:
          type: string
          description: ''
          format: event
        CreditCardPositionKeepingLog:
          type: string
          description: ''
          format: log
      description: The Card Transaction Event is one of the specific types of events that is recorded in the Card Transaction Event
    CreditCardPositionLog:
      type: object
      properties:
        CreditCardPositionLogParameterType:
          type: string
          description: A Classification value that distinguishes between business service events logged within Credit Card Position Log
          format: text
        CreditCardPositionLogSelectedOption:
          type: string
          description: A selected optional business service as subject matter of Credit Card Position Log
          format: service
        CreditCardPositionLogType:
          type: string
          description: The type of Credit Card Position Log
          format: text
        CreditCardPositionLogSchedule:
          type: string
          description: Timetable to track Credit Card Position Log
          format: schedule
        CreditCardPositionLogUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Credit Card Position Log
          format: log
        CreditCardPositionLogUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Credit Card Position Log
          format: log
        CreditCardPositionLogAssociatedParty:
          type: string
          description: Reference to the party who is involved in Credit Card Position Log
          format: involvedparty
        CreditCardPositionLogBusinessUnitReference:
          type: string
          description: Reference to the business unit which is involved in Credit Card Position Log
          format: businessunit
        CreditCardPositionLogCustomerReference:
          type: string
          description: Reference to the customer who is involved in Credit Card Position Log
          format: involvedparty
        CreditCardPositionLogServiceConfiguration:
          type: string
          description: The configuration of Credit Card Position Log
          format: text
        CreditCardPositionLogPosition:
          type: string
          description: The position of Credit Card Position Log
          format: position
        CreditCardPositionLogPositionType:
          type: string
          description: A classification value expressing the kind of position withing the Credit Card Position Log
          format: positiontype
        CreditCardPositionLogPositionLimitTime:
          type: string
          description: Reference to the time limitation related to the position of Credit Card Position Log
          format: limitarrangement
        CreditCardPositionLogReference:
          type: string
          description: An unique reference to an item or an occurrence of Credit Card Position Log
          format: log
      description: 'Maintain a log of transactions or activity, typically a financial account/journal or a log of activity to support behavioral analysis within Credit Card Position Keeping. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    CreditCardPositionLog:
      description: CreditCardPositionLog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreditCardPositionLog'
    CardTransactionEvent:
      description: CardTransactionEvent
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CardTransactionEvent'
  parameters:
    creditcardpositionkeepingid:
      name: creditcardpositionkeepingid
      in: path
      required: true
      style: simple
      schema:
        type: string
    cardtransactioneventid:
      name: cardtransactioneventid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    CreditCardPositionLog:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreditCardPositionLog'
      required: true
    CardTransactionEvent:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CardTransactionEvent'
      required: true