openapi: 3.0.1
info:
  title: Credit Risk Operations
  description: This Service Domain monitors counterparty credit limits in the trading unit
  contact:
    name: BIAN
    url: https://bian.org
  version: 11.0.0
servers:
  - url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/CreditRiskOperations/11.0.0
paths:
  '/CreditRiskOperations/{creditriskoperationsid}/Control':
    put:
      tags:
        - CR - TradingCreditPositionMeasurement
      summary: Control Trading Credit Position Measurement
      description: Control Trading Credit Position Measurement
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
      requestBody:
        $ref: '#/components/requestBodies/TradingCreditPositionMeasurement'
      responses:
        '200':
          $ref: '#/components/responses/TradingCreditPositionMeasurement'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /CreditRiskOperations/Evaluate:
    post:
      tags:
        - CR - TradingCreditPositionMeasurement
      summary: Evaluate Trading Credit Position Measurement
      description: Evaluate Trading Credit Position Measurement
      operationId: Evaluate
      requestBody:
        $ref: '#/components/requestBodies/TradingCreditPositionMeasurement'
      responses:
        '200':
          $ref: '#/components/responses/TradingCreditPositionMeasurement'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/Execute':
    put:
      tags:
        - CR - TradingCreditPositionMeasurement
      summary: Execute Trading Credit Position Measurement
      description: Execute Trading Credit Position Measurement
      operationId: Execute
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
      requestBody:
        $ref: '#/components/requestBodies/TradingCreditPositionMeasurement'
      responses:
        '200':
          $ref: '#/components/responses/TradingCreditPositionMeasurement'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/Notify':
    get:
      tags:
        - CR - TradingCreditPositionMeasurement
      summary: Notify Trading Credit Position Measurement
      description: Notify Trading Credit Position Measurement
      operationId: Notify
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
      responses:
        '200':
          $ref: '#/components/responses/TradingCreditPositionMeasurement'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/Request':
    put:
      tags:
        - CR - TradingCreditPositionMeasurement
      summary: Request Trading Credit Position Measurement
      description: Request Trading Credit Position Measurement
      operationId: Request
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
      requestBody:
        $ref: '#/components/requestBodies/TradingCreditPositionMeasurement'
      responses:
        '200':
          $ref: '#/components/responses/TradingCreditPositionMeasurement'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/TradingCounterpartyCreditLimitIndicator/{tradingcounterpartycreditlimitindicatorid}/Evaluate':
    post:
      tags:
        - BQ - TradingCounterpartyCreditLimitIndicator
      summary: Evaluate Trading Counterparty Credit Limit Indicator
      description: Evaluate Trading Counterparty Credit Limit Indicator
      operationId: EvaluateTradingCounterpartyCreditLimitIndicator
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
        - $ref: '#/components/parameters/tradingcounterpartycreditlimitindicatorid'
      requestBody:
        $ref: '#/components/requestBodies/TradingCounterpartyCreditLimitIndicator'
      responses:
        '200':
          $ref: '#/components/responses/TradingCounterpartyCreditLimitIndicator'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/TradingCounterpartyCreditLimitIndicator/{tradingcounterpartycreditlimitindicatorid}/Execute':
    put:
      tags:
        - BQ - TradingCounterpartyCreditLimitIndicator
      summary: Execute Trading Counterparty Credit Limit Indicator
      description: Execute Trading Counterparty Credit Limit Indicator
      operationId: ExecuteTradingCounterpartyCreditLimitIndicator
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
        - $ref: '#/components/parameters/tradingcounterpartycreditlimitindicatorid'
      requestBody:
        $ref: '#/components/requestBodies/TradingCounterpartyCreditLimitIndicator'
      responses:
        '200':
          $ref: '#/components/responses/TradingCounterpartyCreditLimitIndicator'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/TradingCounterpartyCreditLimitIndicator/{tradingcounterpartycreditlimitindicatorid}/Notify':
    get:
      tags:
        - BQ - TradingCounterpartyCreditLimitIndicator
      summary: Notify Trading Counterparty Credit Limit Indicator
      description: Notify Trading Counterparty Credit Limit Indicator
      operationId: NotifyTradingCounterpartyCreditLimitIndicator
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
        - $ref: '#/components/parameters/tradingcounterpartycreditlimitindicatorid'
      responses:
        '200':
          $ref: '#/components/responses/TradingCounterpartyCreditLimitIndicator'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/TradingCounterpartyCreditLimitIndicator/{tradingcounterpartycreditlimitindicatorid}/Request':
    put:
      tags:
        - BQ - TradingCounterpartyCreditLimitIndicator
      summary: Request Trading Counterparty Credit Limit Indicator
      description: Request Trading Counterparty Credit Limit Indicator
      operationId: RequestTradingCounterpartyCreditLimitIndicator
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
        - $ref: '#/components/parameters/tradingcounterpartycreditlimitindicatorid'
      requestBody:
        $ref: '#/components/requestBodies/TradingCounterpartyCreditLimitIndicator'
      responses:
        '200':
          $ref: '#/components/responses/TradingCounterpartyCreditLimitIndicator'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditRiskOperations/{creditriskoperationsid}/TradingCounterpartyCreditLimitIndicator/{tradingcounterpartycreditlimitindicatorid}/Retrieve':
    get:
      tags:
        - BQ - TradingCounterpartyCreditLimitIndicator
      summary: Retrieve Trading Counterparty Credit Limit Indicator
      description: Retrieve Trading Counterparty Credit Limit Indicator
      operationId: RetrieveTradingCounterpartyCreditLimitIndicator
      parameters:
        - $ref: '#/components/parameters/creditriskoperationsid'
        - $ref: '#/components/parameters/tradingcounterpartycreditlimitindicatorid'
      responses:
        '200':
          $ref: '#/components/responses/TradingCounterpartyCreditLimitIndicator'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    TradingCounterpartyCreditLimitIndicator:
      type: object
      properties:
        TradingCreditPositionMeasurementReference:
          type: string
          description: Reference to Trading Counterparty Credit Limit Indicator
          format: object
        TradingCounterpartyCreditLimitIndicatorReference:
          type: string
          description: Reference to Trading Counterparty Credit Limit Indicator
          format: object
        TradingCounterpartyCreditLimitIndicatorType:
          type: string
          description: The type of Trading Counterparty Credit Limit Indicator
          format: text
        BusinessService:
          type: string
          description: The Trading Counterparty Credit Limit Indicator specific Business Service
          format: businessservice
        BusinessUnitEmployeeReference:
          type: string
          description: The operating unit/employee responsible for monitoring Trading Counterparty Credit Limit Indicator by applying the Trading Counterparty Credit Limit Indicator indicator
          format: involvedparty
        Postconditions:
          type: string
          description: The completion status once Trading Counterparty Credit Limit Indicator has been monitored by applying the Trading Counterparty Credit Limit Indicator indicator
          format: condition
        Preconditions:
          type: string
          description: The required status/situation before Trading Counterparty Credit Limit Indicator can be monitored by applying the Trading Counterparty Credit Limit Indicator indicator
          format: condition
        Schedule:
          type: string
          description: The timing and key actions/milestones involved in monitoring Trading Counterparty Credit Limit Indicator by applying the Trading Counterparty Credit Limit Indicator indicator
          format: schedule
      description: 'The Trading Counterparty Credit Limit Indicator is one integral indicator that can be included in Trading Counterparty Credit Limit Indicator monitoring '
    CreditRiskOperationsOutcome:
      type: object
      properties:
        CreditRiskOperationsDashboard:
          type: string
          description: ''
          format: text
      description: 'The Trading Counterparty Credit Limit Indicator is one integral indicator that can be included in Trading Counterparty Credit Limit Indicator monitoring '
    TradingCreditPositionMeasurement:
      type: object
      properties:
        TradingCreditPositionMeasurementParameterType:
          type: string
          description: A Classification value that distinguishes between states according to the type of business services and/or type of concern defined within Trading Credit Position Measurement
          format: text
        TradingCreditPositionMeasurementSelectedOption:
          type: string
          description: A selected optional business service as subject matter of Trading Credit Position Measurement
          format: businessservice
        TradingCreditPositionMeasurementType:
          type: string
          description: The type of Trading Credit Position Measurement
          format: text
        TradingCreditPositionMeasurementReference:
          type: string
          description: An unique reference to an item or an occurrence of Trading Credit Position Measurement
          format: object
        TradingCreditPositionMeasurementDescription:
          type: string
          description: Documentation of Trading Credit Position Measurement
          format: text
        TradingCreditPositionMeasurementSchedule:
          type: string
          description: Timetable to monitor Trading Credit Position Measurement
          format: schedule
        TradingCreditPositionMeasurementStatus:
          type: string
          description: The status of Trading Credit Position Measurement
          format: status
        TradingCreditPositionMeasurementUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Trading Credit Position Measurement
          format: log
        TradingCreditPositionMeasurementUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Trading Credit Position Measurement
          format: log
        TradingCreditPositionMeasurementCustomerReference:
          type: string
          description: Reference to the customer who is involved in Trading Credit Position Measurement
          format: involvedparty
        TradingCreditPositionMeasurementProductReference:
          type: string
          description: Reference to the product which is the subject matter of Trading Credit Position Measurement
          format: bankingproduct
        TradingCreditPositionMeasurementServiceConfiguration:
          type: string
          description: The configuration of Trading Credit Position Measurement
          format: text
        TradingCreditPositionMeasurementServiceConfigurationTresholdsandLimits:
          type: string
          description: Reference to Tresholds and Limits for monitoring Trading Credit Position Measurement
          format: limitarrangement
        TradingCreditPositionMeasurementServiceConfigurationNotificationArrangements:
          type: string
          description: Reference to Notification Arrangements for monitoring Trading Credit Position Measurement
          format: arrangement
      description: 'Monitor and define the status/rating of some entity within Credit Risk Operations. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TradingCreditPositionMeasurement:
      description: TradingCreditPositionMeasurement
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TradingCreditPositionMeasurement'
    TradingCounterpartyCreditLimitIndicator:
      description: TradingCounterpartyCreditLimitIndicator
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TradingCounterpartyCreditLimitIndicator'
  parameters:
    creditriskoperationsid:
      name: creditriskoperationsid
      in: path
      required: true
      style: simple
      schema:
        type: string
    tradingcounterpartycreditlimitindicatorid:
      name: tradingcounterpartycreditlimitindicatorid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    TradingCreditPositionMeasurement:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TradingCreditPositionMeasurement'
      required: true
    TradingCounterpartyCreditLimitIndicator:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TradingCounterpartyCreditLimitIndicator'
      required: true