openapi: 3.0.1
info:
  title: Information Provider Operation
  description: ''
  contact:
    name: BIAN
    url: https://bian.org
  version: 11.0.0
servers:
  - url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/InformationProviderOperation/11.0.0
paths:
  '/InformationProviderOperation/{informationprovideroperationid}/Control':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Control Information Feed Operating Session
      description: Control Information Feed Operating Session
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Exchange':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Exchange Information Feed Operating Session
      description: Exchange Information Feed Operating Session
      operationId: Exchange
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Execute':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Execute Information Feed Operating Session
      description: Execute Information Feed Operating Session
      operationId: Execute
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/Initiate:
    post:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Initiate Information Feed Operating Session
      description: Initiate Information Feed Operating Session
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Notify':
    get:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Notify Information Feed Operating Session
      description: Notify Information Feed Operating Session
      operationId: Notify
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Request':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Request Information Feed Operating Session
      description: Request Information Feed Operating Session
      operationId: Request
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    event:
      type: object
      properties:
        EventType:
          type: string
          description: ''
          format: string
        EventDateTime:
          type: string
          description: ''
          format: string
        EventDescription:
          type: string
          description: ''
          format: string
        EventSource:
          type: string
          description: ''
          format: string
        EventLocation:
          type: string
          description: ''
          format: string
        EventAction:
          type: string
          description: ''
          format: string
        EventStatus:
          type: string
          description: ''
          format: string
        EventValue:
          type: string
          description: ''
          format: string
        EventValidityPeriod:
          type: string
          description: ''
          format: string
        EventIdentification:
          type: string
          description: ''
          format: string
      description: ''
    text:
      type: object
      properties:
        Text:
          type: string
          description: Text is a character string such as a finite set of characters generally in the form of words of a language. (UN/CEFACT)
          format: datatype
      description: ''
    InformationProviderOperationOutcome:
      type: object
      properties:
        InformationProviderOperationIncident:
          $ref: '#/components/schemas/event'
        InformationProviderOperationProvision:
          $ref: '#/components/schemas/text'
      description: "The collection of operational serivces/functions offered by the operational facility\n\nExamples: messages, capture, routines"
    schedule:
      type: object
      properties:
        ScheduleType:
          type: string
          description: ''
          format: string
      description: Timetable to operate Information Feed Operating Session
    datetime:
      type: object
      properties:
        DateTimeContent:
          type: string
          description: ''
          format: string
        TimeZoneCode:
          type: string
          description: ''
          format: string
        DaylightSavingIndicator:
          type: string
          description: ''
          format: string
      description: Date and time at which the status was assigned.
    datetimeperiod:
      type: object
      properties:
        FromDateTime:
          $ref: '#/components/schemas/datetime'
        ToDateTime:
          $ref: '#/components/schemas/datetime'
      description: Period of time during which the status is valid.
    name:
      type: object
      properties:
        Name:
          type: string
          description: 'A name is a word or phrase that constitutes the distinctive designation of a person, place, thing or concept. (UN/CEFAT)'
          format: datatype
      description: Name by which a party is known and which is usually used to identify that party. (ISO20022)
    partytypevalues:
      enum:
        - Person
        - Organisation
      type: string
      description: ">\n* `Person` - Human entity, as distinguished from a corporate entity (which is sometimes referred to as an 'artificial person'). ISO20022\n* `Organisation` - Organised structure that is set up for a particular purpose. For example, a business, government body, department, charity, or financial institution. ISO20022\n"
    value:
      type: object
      properties:
        Value:
          type: string
          description: 'A value is the concept of worth in general that is assigned or is determined by measurement, assessment or calculation. (UN/CEFACT)'
          format: datatype
      description: ''
    identifier:
      type: object
      properties:
        IdentifierValue:
          $ref: '#/components/schemas/value'
        IdentifierIssuingAuthority:
          $ref: '#/components/schemas/involvedparty'
        IdentifierStartDate:
          $ref: '#/components/schemas/datetime'
        IdentifierEndDate:
          $ref: '#/components/schemas/datetime'
      description: ''
    partyidentification:
      type: object
      properties:
        PartyIdentificationType:
          type: string
          description: ''
          format: partyidentificationtypevalues
        PartyIdentification:
          $ref: '#/components/schemas/identifier'
      description: ''
    party:
      type: object
      properties:
        PartyName:
          $ref: '#/components/schemas/name'
        PartyType:
          $ref: '#/components/schemas/partytypevalues'
        PartyDateTime:
          $ref: '#/components/schemas/datetime'
        PartyIdentification:
          $ref: '#/components/schemas/partyidentification'
      description: ''
    partyinvolvementtypevalues:
      enum:
        - Agreementinvolvement
        - Partyinvolvement
        - Arrangementinvolvement
        - Designspecificationinvolvement
        - Relationshipinvolvement
        - Locationinvolvement
        - Bankguaranteeinvolvement
      type: string
      description: ">\n* `Agreementinvolvement` - \n* `Partyinvolvement` - \n* `Arrangementinvolvement` - \n* `Designspecificationinvolvement` - \n* `Relationshipinvolvement` - \n* `Locationinvolvement` - \n* `Bankguaranteeinvolvement` - \n"
    partyrole:
      type: object
      properties:
        PartyRoleType:
          $ref: '#/components/schemas/text'
        PartyRoleName:
          $ref: '#/components/schemas/name'
        PartyRoleValidityPeriod:
          $ref: '#/components/schemas/datetimeperiod'
        PartyInvolvementType:
          $ref: '#/components/schemas/partyinvolvementtypevalues'
      description: ''
    involvedparty:
      type: object
      properties:
        PartyReference:
          $ref: '#/components/schemas/party'
        PartyInvolvement:
          $ref: '#/components/schemas/partyrole'
      description: Party who plays a  specific role in the context of assigning a status.
    status:
      type: object
      properties:
        StatusReason:
          $ref: '#/components/schemas/text'
        StatusDateTime:
          $ref: '#/components/schemas/datetime'
        StatusValidityPeriod:
          $ref: '#/components/schemas/datetimeperiod'
        StatusInvolvedParty:
          $ref: '#/components/schemas/involvedparty'
      description: The status of Information Feed Operating Session
    log:
      type: object
      properties:
        LogType:
          type: string
          description: ''
          format: string
        LogPeriod:
          type: string
          description: ''
          format: string
        LogDate:
          type: string
          description: Key dates associated with the log (e.g. start time).
          format: string
        LogIdentification:
          type: string
          description: ''
          format: string
      description: Reference to the log of (usage) ativities/events  of Information Feed Operating Session
    sessiontype:
      type: object
      properties:
        SessionTypeName:
          $ref: '#/components/schemas/name'
        SessionType:
          type: string
          description: ''
          format: sessiontypevalues
      description: A Classification value that distinguishes between the type of operations within Information Feed Operating Session
    servicetype:
      type: object
      properties:
        ServiceTypeName:
          $ref: '#/components/schemas/name'
        ServiceType:
          type: string
          description: ''
          format: servicetypevalues
      description: A Classification value that distinguishes between the type of services within Information Feed Operating Session
    systemconfigurationoption:
      type: object
      properties:
        SystemConfigurationOption:
          type: string
          description: "Options for configuring the system or the function/feature of system.\n"
          format: class
      description: The configuration of Information Feed Operating Session
    duration:
      type: object
      properties:
        Duration:
          type: string
          description: 'A duration is the specification of a length of time without a fixed start or end time, expressed in Gregorian calendar time units (Year, Month, Week, Day) and Hours, Minutes or Seconds. (UN/CEFACT)'
          format: datatype
      description: The time the session was active
    session:
      type: object
      properties:
        SessionDuration:
          $ref: '#/components/schemas/duration'
        SessionDateTime:
          $ref: '#/components/schemas/datetime'
        SessionStatus:
          $ref: '#/components/schemas/status'
        SessionType:
          $ref: '#/components/schemas/sessiontype'
        SessionScheduel:
          $ref: '#/components/schemas/schedule'
      description: An unique reference to an item or an occurrence of Information Feed Operating Session
    InformationFeedOperatingSession:
      type: object
      properties:
        InformationFeedOperatingSessionSchedule:
          $ref: '#/components/schemas/schedule'
        InformationFeedOperatingSessionStatus:
          $ref: '#/components/schemas/status'
        InformationFeedOperatingSessionUsageLog:
          $ref: '#/components/schemas/log'
        InformationFeedOperatingSessionAssociatedPartyReference:
          $ref: '#/components/schemas/involvedparty'
        InformationFeedOperatingSessionServiceProviderReference:
          $ref: '#/components/schemas/involvedparty'
        InformationFeedOperatingSessionType:
          $ref: '#/components/schemas/sessiontype'
        InformationFeedOperatingSessionServiceProviderSchedule:
          $ref: '#/components/schemas/schedule'
        InformationFeedOperatingSessionServiceType:
          $ref: '#/components/schemas/servicetype'
        InformationFeedOperatingSessionServiceConfiguration:
          $ref: '#/components/schemas/systemconfigurationoption'
        InformationFeedOperatingSessionReference:
          $ref: '#/components/schemas/session'
      description: 'Operate equipment and/or a largely automated facility within Information Provider Operation. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InformationFeedOperatingSession:
      description: InformationFeedOperatingSession
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
  parameters:
    informationprovideroperationid:
      name: informationprovideroperationid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    InformationFeedOperatingSession:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
      required: true