openapi: 3.0.1
info:
  title: Internal Bank Account
  description: This Service Domain manages the banking-related accounts that are not owned by customers. These are not general ledger accounts. Typical examples are holding accounts and mirror accounts.
  contact:
    name: BIAN
    url: https://bian.org
  version: 11.0.0
servers:
  - url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/InternalBankAccount/11.0.0
paths:
  '/InternalBankAccount/{internalbankaccountid}/Capture':
    put:
      tags:
        - CR - InternalBankAccountLog
      summary: Capture Internal Bank Account Log
      description: Capture Internal Bank Account Log
      operationId: Capture
      parameters:
        - $ref: '#/components/parameters/internalbankaccountid'
      requestBody:
        $ref: '#/components/requestBodies/InternalBankAccountLog'
      responses:
        '200':
          $ref: '#/components/responses/InternalBankAccountLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InternalBankAccount/{internalbankaccountid}/Control':
    put:
      tags:
        - CR - InternalBankAccountLog
      summary: Control Internal Bank Account Log
      description: Control Internal Bank Account Log
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/internalbankaccountid'
      requestBody:
        $ref: '#/components/requestBodies/InternalBankAccountLog'
      responses:
        '200':
          $ref: '#/components/responses/InternalBankAccountLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InternalBankAccount/{internalbankaccountid}/Notify':
    get:
      tags:
        - CR - InternalBankAccountLog
      summary: Notify Internal Bank Account Log
      description: Notify Internal Bank Account Log
      operationId: Notify
      parameters:
        - $ref: '#/components/parameters/internalbankaccountid'
      responses:
        '200':
          $ref: '#/components/responses/InternalBankAccountLog'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    InternalBankAccountLog:
      type: object
      properties:
        InternalBankAccountLogParameterType:
          type: string
          description: A Classification value that distinguishes between business service events logged within Internal Bank Account Log
          format: text
        InternalBankAccountLogSelectedOption:
          type: string
          description: A selected optional business service as subject matter of Internal Bank Account Log
          format: service
        InternalBankAccountLogType:
          type: string
          description: The type of Internal Bank Account Log
          format: text
        InternalBankAccountLogSchedule:
          type: string
          description: Timetable to track Internal Bank Account Log
          format: schedule
        InternalBankAccountLogUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Internal Bank Account Log
          format: log
        InternalBankAccountLogUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Internal Bank Account Log
          format: log
        InternalBankAccountLogAssociatedParty:
          type: string
          description: Reference to the party who is involved in Internal Bank Account Log
          format: involvedparty
        InternalBankAccountLogBusinessUnitReference:
          type: string
          description: Reference to the business unit which is involved in Internal Bank Account Log
          format: businessunit
        InternalBankAccountLogCustomerReference:
          type: string
          description: Reference to the customer who is involved in Internal Bank Account Log
          format: involvedparty
        InternalBankAccountLogServiceConfiguration:
          type: string
          description: The configuration of Internal Bank Account Log
          format: text
        InternalBankAccountLogPosition:
          type: string
          description: The position of Internal Bank Account Log
          format: position
        InternalBankAccountLogPositionType:
          type: string
          description: A classification value expressing the kind of position withing the Internal Bank Account Log
          format: positiontype
        InternalBankAccountLogPositionLimitTime:
          type: string
          description: Reference to the time limitation related to the position of Internal Bank Account Log
          format: limitarrangement
        InternalBankAccountLogReference:
          type: string
          description: An unique reference to an item or an occurrence of Internal Bank Account Log
          format: log
      description: 'Maintain a log of transactions or activity, typically a financial account/journal or a log of activity to support behavioral analysis within Internal Bank Account. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalBankAccountLog:
      description: InternalBankAccountLog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalBankAccountLog'
  parameters:
    internalbankaccountid:
      name: internalbankaccountid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    InternalBankAccountLog:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalBankAccountLog'
      required: true